import type { GameUIConfig } from '../gameUIConfig.types';

export const cognitiveLearningConfigs: Partial<Record<string, GameUIConfig>> = {
  "virtual-reality": {
    title: "🥽 משחק מציאות מדומה 🌐",
    subTitle: "גלה את עולם הטכנולוגיה המתקדמת!",
    itemsTitle: "טכנולוגיות VR שנלמד:",
    itemsDescription: "לחץ על טכנולוגיה כדי לשמוע עליה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו טכנולוגיה אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלה" },
      { icon: "👆", title: "3. תלחץ", description: "על הטכנולוגיה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "purple" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו טכנולוגיה שמעת?",
    challengeIcon: "🥽🌐💻🎮",
    challengeDescription: "בחר את הטכנולוגיה הנכונה!",
    itemLabel: "טכנולוגיה",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הטכנולוגיות למטה לשמוע את השמות",
    metadata: {
      keywords: "מציאות מדומה, VR, טכנולוגיה, מחשב, גיל 7-12, עתיד, חדשנות טכנולוגית",
      description: "גלו עולם הטכנולוגיה המתקדמת! מציאות מדומה, בינה מלאכותית ועוד — לגיל 7-12.",
    },
  },

  "new-professions": {
    title: "👨‍💻 משחק מקצועות חדשים 👩‍🚀",
    subTitle: "מקצועות העתיד כבר כאן!",
    itemsTitle: "מקצועות העתיד שנלמד:",
    itemsDescription: "לחץ על מקצוע כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה מקצוע אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על המקצוע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #00c9ff 0%, #92fe9d 25%, #00d2ff 50%, #3a7bd5 75%, #00d2ff 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "cyan", to: "blue" },
      stepsBg: "bg-cyan-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה מקצוע שמעת?",
    challengeIcon: "👨‍💻👩‍🚀🤖🎯",
    challengeDescription: "בחר את המקצוע הנכון!",
    itemLabel: "מקצוע",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המקצועות למטה לשמוע את השמות",
    metadata: {
      keywords: "מקצועות עתיד, מתכנת, אסטרונאוט, מדען, גיל 7-12, קריירה, מקצועות מודרניים",
      description: "למדו על מקצועות העתיד המרתקים! מתכנת, אסטרונאוט, מדען ועוד — לגיל 7-12.",
    },
  },

  "advanced-weather": {
    title: "🌪️ משחק מזג אוויר מתקדם ⚡",
    subTitle: "תופעות מזג אוויר מרהיבות!",
    itemsTitle: "תופעות מזג אוויר שנלמד:",
    itemsDescription: "לחץ על תופעה כדי לשמוע עליה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו תופעה אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלה" },
      { icon: "👆", title: "3. תלחץ", description: "על התופעה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #74b9ff 0%, #0984e3 25%, #6c5ce7 50%, #a29bfe 75%, #fd79a8 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו תופעת מזג אוויר שמעת?",
    challengeIcon: "🌪️⚡🌀❄️",
    challengeDescription: "בחר את התופעה הנכונה!",
    itemLabel: "תופעת מזג אוויר",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על התופעות למטה לשמוע את השמות",
    metadata: {
      keywords: "מזג אוויר מתקדם, סופת ברקים, הוריקן, ברד, אקלים, גיל 7-12, תופעות טבע",
      description: "גלו תופעות מזג אוויר קיצוניות ומרהיבות! ברקים, הוריקן, ברד ועוד — לגיל 7-12.",
    },
  },

  "advanced-colors": {
    title: "🎨 משחק צבעים מתקדם 💎",
    subTitle: "גוונים וצבעים מיוחדים!",
    itemsTitle: "צבעים מיוחדים שנלמד:",
    itemsDescription: "לחץ על צבע כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה צבע אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על הצבע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff7675 0%, #fdcb6e 25%, #6c5ce7 50%, #00b894 75%, #e17055 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "red" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה צבע שמעת?",
    challengeIcon: "🎨💎🪸🟣",
    challengeDescription: "בחר את הצבע הנכון!",
    itemLabel: "צבע",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצבעים למטה לשמוע את השמות",
    metadata: {
      keywords: "צבעים מתקדמים, גוונים, טורקיז, לילך, שנהב, אמנות, גיל 5-10, ציור",
      description: "למדו גוונים וצבעים מיוחדים! טורקיז, לילך, קורל ועוד — העשרת אוצר הצבע לגיל 5-10.",
    },
  },

  "jewish-holidays": {
    title: "🕯️ משחק חגים יהודיים 📜",
    subTitle: "למד על חגי ישראל המיוחדים!",
    itemsTitle: "חגים יהודיים שנלמד:",
    itemsDescription: "לחץ על חג כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה חג אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על החג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 25%, #ff9a9e 50%, #fecfef 75%, #fecfef 100%)",
      header: "text-purple-800",
      subHeader: "text-purple-700",
      itemsDescription: "text-purple-700",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה חג יהודי שמעת?",
    challengeIcon: "🕯️📜✡️🍯",
    challengeDescription: "בחר את החג הנכון!",
    itemLabel: "חג יהודי",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על החגים למטה לשמוע את השמות",
    metadata: {
      keywords: "חגים יהודיים, ראש השנה, יום כיפור, פסח, חנוכה, פורים, סוכות, גיל 4-10",
      description: "למדו חגים יהודיים מיוחדים! ראש השנה, פסח, חנוכה ועוד — מסורת ישראלית לגיל 4-10.",
    },
  },

  "logic-games": {
    title: "🧩 משחק משחקי לוגיקה 🎯",
    subTitle: "פתח את כושר החשיבה שלך!",
    itemsTitle: "משחקי לוגיקה שנלמד:",
    itemsDescription: "לחץ על משחק כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה משחק אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על המשחק הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-indigo-100",
      itemsDescription: "text-indigo-100",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה משחק לוגיקה שמעת?",
    challengeIcon: "🧩🎯♟️🎲",
    challengeDescription: "בחר את המשחק הנכון!",
    itemLabel: "משחק לוגיקה",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המשחקים למטה לשמוע את השמות",
    metadata: {
      keywords: "לוגיקה, חשיבה ביקורתית, שח, פאזל, אסטרטגיה, גיל 6-12, חידות לוגיות",
      description: "פתחו חשיבה לוגית ואסטרטגית! שח, פאזלים, חידות ועוד — לגיל 6-12.",
    },
  },

  "time-clock": {
    title: "⏰ משחק זמן ושעות היום 📅",
    subTitle: "למד על זמן, שעות וזמנים מיוחדים!",
    itemsTitle: "מושגי זמן שנלמד:",
    itemsDescription: "לחץ על מושג זמן כדי ללמוד עליו!",
    steps: [
      { icon: "🕐", title: "1. תראה", description: "איזה זמן אני מציג" },
      { icon: "🧠", title: "2. תחשוב", description: "מתי זה קורה ביום" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הזמן הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #4facfe 0%, #00f2fe 25%, #43e97b 50%, #38f9d7 75%, #667eea 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "cyan" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-4 gap-4 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה זמן זה?",
    challengeIcon: "⏰📅🌅🌙",
    challengeDescription: "זהה את הזמן ובחר את התשובה הנכונה!",
    itemLabel: "זמן",
    tip: "💡 טיפ: חשוב על היום שלך!",
    tipDescription: "חשוב מה אתה עושה בזמנים שונים ביום, ואז בחר",
    metadata: {
      keywords: "שעות היום, זמן, בוקר, צהריים, ערב, לילה, שעון, גיל 5-9, לוח זמנים",
      description: "למדו על שעות היום ומושגי זמן! בוקר, צהריים, ערב ולילה — לגיל 5-9.",
    },
  },
};
