Remove-Item "app\games\bubbles\components\Bubble.tsx" -Force
Remove-Item "app\games\bubbles\components\BubbleGame.tsx" -Force
Remove-Item "app\games\bubbles\components\BubbleStartScreen.tsx" -Force
Remove-Item "app\games\bubbles\hooks\useBubbleGame.ts" -Force
Remove-Item "app\games\counting\components\CountingCard.tsx" -Force
Remove-Item "app\games\counting\components\CountingStartScreen.tsx" -Force
Remove-Item "app\games\counting\useCountingGame.ts" -Force
Remove-Item "app\games\drawing\components\DrawingGameClient.tsx" -Force
Remove-Item "app\games\drawing\components\DrawingTools.tsx" -Force
Remove-Item "app\games\drawing\hooks\useDrawingCanvas.ts" -Force
Remove-Item "app\games\drawing\hooks\useDrawingGame.ts" -Force
Remove-Item "app\games\hebrew-letters\components\HebrewLetterPractice.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\HebrewLetterProgress.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\HebrewLettersHub.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\HebrewLettersStats.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\HebrewLettersStatsPanel.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\LetterEncouragement.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\LetterGuideOverlay.tsx" -Force
Remove-Item "app\games\hebrew-letters\components\WritingCanvas.tsx" -Force
Remove-Item "app\games\hebrew-letters\constants\hebrewLetters.ts" -Force
Remove-Item "app\games\hebrew-letters\constants\hebrewLettersConstants.ts" -Force
Remove-Item "app\games\hebrew-letters\contexts\HebrewLettersContext.tsx" -Force
Remove-Item "app\games\hebrew-letters\contexts\hebrewLettersUtils.ts" -Force
Remove-Item "app\games\hebrew-letters\contexts\operations\audioOperations.ts" -Force
Remove-Item "app\games\hebrew-letters\contexts\operations\drawingOperations.ts" -Force
Remove-Item "app\games\hebrew-letters\contexts\operations\practiceOperations.ts" -Force
Remove-Item "app\games\hebrew-letters\hooks\useHebrewLetterPractice.ts" -Force
Remove-Item "app\games\hebrew-letters\hooks\useHebrewLettersStats.ts" -Force
Remove-Item "app\games\math\components\MathNumberCard.tsx" -Force
Remove-Item "app\games\math\components\MathStartScreen.tsx" -Force
Remove-Item "app\games\math\components\StartScreen.tsx" -Force
Remove-Item "app\games\math\hooks\useMathGame.ts" -Force
Remove-Item "app\games\memory\components\GameWinMessage.tsx" -Force
Remove-Item "app\games\memory\components\MemoryCard.tsx" -Force
Remove-Item "app\games\memory\components\MemoryGameBoard.tsx" -Force
Remove-Item "app\games\memory\components\MemoryGameHeader.tsx" -Force
Remove-Item "app\games\memory\components\MemoryStartScreen.tsx" -Force
Remove-Item "app\games\memory\contexts\MemoryContext.tsx" -Force
Remove-Item "app\games\puzzles\components\FeedbackMessage.tsx" -Force
Remove-Item "app\games\puzzles\components\FloatingDragPiece.tsx" -Force
Remove-Item "app\games\puzzles\components\ImageUploadSection.tsx" -Force
Remove-Item "app\games\puzzles\components\PiecesPool.tsx" -Force
Remove-Item "app\games\puzzles\components\PuzzleGrid.tsx" -Force
Remove-Item "app\games\puzzles\components\PuzzleSelector.tsx" -Force
Remove-Item "app\games\puzzles\components\PuzzleStats.tsx" -Force
Remove-Item "app\games\puzzles\components\ReferenceImage.tsx" -Force
Remove-Item "app\games\puzzles\components\UnifiedControls.tsx" -Force
Remove-Item "app\games\puzzles\components\UnifiedHeader.tsx" -Force
Remove-Item "app\games\puzzles\components\UnifiedHelpModal.tsx" -Force
Remove-Item "app\games\puzzles\constants\simplePuzzlesData.ts" -Force
Remove-Item "app\games\puzzles\contexts\PuzzleContext.tsx" -Force
Remove-Item "app\games\puzzles\CustomPuzzleGame.tsx" -Force
Remove-Item "app\games\puzzles\handlers\dragHandlers.ts" -Force
Remove-Item "app\games\puzzles\hooks\usePuzzleFeedback.ts" -Force
Remove-Item "app\games\puzzles\logic\puzzleGameLogic.ts" -Force
Remove-Item "app\games\puzzles\SimplePuzzleGame.tsx" -Force
Remove-Item "app\games\puzzles\state\puzzleReducer.ts" -Force
Remove-Item "app\games\puzzles\types\puzzle.ts" -Force
Remove-Item "app\games\puzzles\utils\puzzleUtils.ts" -Force
Remove-Item "app\games\tetris\components\AnimatedBackground.tsx" -Force
Remove-Item "app\games\tetris\components\GameBoard.tsx" -Force
Remove-Item "app\games\tetris\components\InfoPanels.tsx" -Force
Remove-Item "app\games\tetris\components\LoadingScreen.tsx" -Force
Remove-Item "app\games\tetris\components\NextPieceDisplay.tsx" -Force
Remove-Item "app\games\tetris\components\TetrisGame.tsx" -Force
Remove-Item "app\games\tetris\components\TouchControls.tsx" -Force
Remove-Item "app\games\tetris\constants.ts" -Force
Remove-Item "app\games\tetris\hooks\useTetrisGame.ts" -Force
Remove-Item "app\games\tzedakah\CharityCoinGame.tsx" -Force
Remove-Item "app\games\tzedakah\components\CharityBasket.tsx" -Force
Remove-Item "app\games\tzedakah\components\CharityCoin.tsx" -Force
Remove-Item "app\games\tzedakah\components\CharityGameHeader.tsx" -Force
Remove-Item "app\games\tzedakah\components\GameAreaBackground.tsx" -Force
Remove-Item "app\games\tzedakah\components\GameControls.tsx" -Force
Remove-Item "app\games\tzedakah\components\TzedakahGameInstructions.tsx" -Force
Remove-Item "app\HomePageClient.tsx" -Force
Remove-Item "app\not-found.tsx" -Force
Remove-Item "app\sitemap.ts" -Force
Remove-Item "components\analytics\GoogleAnalytics.tsx" -Force
Remove-Item "components\analytics\ServiceWorkerRegistration.tsx" -Force
Remove-Item "components\game\AgeGroupCard.tsx" -Force
Remove-Item "components\game\AllGamesView.tsx" -Force
Remove-Item "components\game\CategoriesView.tsx" -Force
Remove-Item "components\game\CategoryCard.tsx" -Force
Remove-Item "components\game\CategoryGamesView.tsx" -Force
Remove-Item "components\game\CategoryNavigation.tsx" -Force
Remove-Item "components\game\FeaturedGameCallToAction.tsx" -Force
Remove-Item "components\game\GameCard.tsx" -Force
Remove-Item "components\game\RecommendationsHeader.tsx" -Force
Remove-Item "components\game\universal\AutoGamePage.tsx" -Force
Remove-Item "components\game\universal\UltimateGamePage.tsx" -Force
Remove-Item "components\game\universal\UniversalGameNavigation.tsx" -Force
Remove-Item "components\layout\Footer.tsx" -Force
Remove-Item "components\layout\Header.tsx" -Force
Remove-Item "components\layout\LoadingScreen.tsx" -Force
Remove-Item "components\layout\StaticHeader.tsx" -Force
Remove-Item "components\marketing\CategorizedGamesGrid.tsx" -Force
Remove-Item "components\marketing\DynamicCallToAction.tsx" -Force
Remove-Item "components\marketing\FeaturedGame.tsx" -Force
Remove-Item "components\marketing\GameRecommendations.tsx" -Force
Remove-Item "components\shared\audio\AudioSettingsPanel.tsx" -Force
Remove-Item "components\shared\buttons\ButtonCheckAudio.tsx" -Force
Remove-Item "components\shared\buttons\GameStartButton.tsx" -Force
Remove-Item "components\shared\buttons\GameStatsButton.tsx" -Force
Remove-Item "components\shared\buttons\SimpleGameStartButton.tsx" -Force
Remove-Item "components\shared\cards\BaseGameCard.tsx" -Force
Remove-Item "components\shared\cards\CardPresets.tsx" -Force
Remove-Item "components\shared\cards\ColoredShapeCard.tsx" -Force
Remove-Item "components\shared\cards\GameCardGrid.tsx" -Force
Remove-Item "components\shared\cards\UnifiedCard.tsx" -Force
Remove-Item "components\shared\displays\GameProgressDisplay.tsx" -Force
Remove-Item "components\shared\displays\GenericBox.tsx" -Force
Remove-Item "components\shared\displays\OptimizedImage.tsx" -Force
Remove-Item "components\shared\displays\ProgressDisplay.tsx" -Force
Remove-Item "components\shared\displays\SimpleProgressDisplay.tsx" -Force
Remove-Item "components\shared\feedback\CelebrationBox.tsx" -Force
Remove-Item "components\shared\feedback\ChallengeBox.tsx" -Force
Remove-Item "components\shared\feedback\GameHints.tsx" -Force
Remove-Item "components\shared\feedback\GameInstructions.tsx" -Force
Remove-Item "components\shared\feedback\SimpleGameInstructions.tsx" -Force
Remove-Item "components\shared\feedback\TipsBox.tsx" -Force
Remove-Item "components\shared\GameChallengeSection.tsx" -Force
Remove-Item "components\shared\GameItem.tsx" -Force
Remove-Item "components\shared\GameMainContent.tsx" -Force
Remove-Item "components\shared\headers\GameHeader.tsx" -Force
Remove-Item "components\shared\headers\GameHeaderSection.tsx" -Force
Remove-Item "components\shared\headers\StartScreenHeader.tsx" -Force
Remove-Item "components\shared\headers\UnifiedHeader.tsx" -Force
Remove-Item "components\shared\performance\PerformanceSettingsPanel.tsx" -Force
Remove-Item "components\shared\screens\AutoStartScreen.tsx" -Force
Remove-Item "components\shared\screens\GameErrorScreen.tsx" -Force
Remove-Item "components\shared\screens\GameLoadingScreen.tsx" -Force
Remove-Item "components\shared\screens\GenericStartScreen.tsx" -Force
Remove-Item "components\user\UserProfile.tsx" -Force
Remove-Item "contexts\AuthContext.tsx" -Force
Remove-Item "contexts\GameConfigContext.tsx" -Force
Remove-Item "contexts\GameLogicContext.tsx" -Force
Remove-Item "contexts\GameProgressContext.tsx" -Force
Remove-Item "contexts\GameTypeContext.tsx" -Force
Remove-Item "contexts\SimpleGameProgressContext.tsx" -Force
Remove-Item "contexts\UniversalGameContext.tsx" -Force
Remove-Item "hooks\games\useGenericGame.ts" -Force
Remove-Item "hooks\games\useSimpleGame.ts" -Force
Remove-Item "hooks\shared\analytics\useGameAnalytics.ts" -Force
Remove-Item "hooks\shared\analytics\useGamePerformance.ts" -Force
Remove-Item "hooks\shared\audio\useAudioSettings.ts" -Force
Remove-Item "hooks\shared\audio\useGameAudio.ts" -Force
Remove-Item "hooks\shared\audio\useSpeechSynthesis.ts" -Force
Remove-Item "hooks\shared\common\useCommonGamePatterns.ts" -Force
Remove-Item "hooks\shared\common\useGameDifficulty.ts" -Force
Remove-Item "hooks\shared\common\useGameSettings.ts" -Force
Remove-Item "hooks\shared\common\usePlayerProfile.ts" -Force
Remove-Item "hooks\shared\game-state\useAdvancedGameState.ts" -Force
Remove-Item "hooks\shared\game-state\useAutoGame.ts" -Force
Remove-Item "hooks\shared\game-state\useBaseGame.ts" -Force
Remove-Item "hooks\shared\game-state\useGameContext.ts" -Force
Remove-Item "hooks\shared\game-state\useGameData.ts" -Force
Remove-Item "hooks\shared\game-state\useGameOptions.ts" -Force
Remove-Item "hooks\shared\performance\useMemoryManagement.ts" -Force
Remove-Item "hooks\shared\progress\useAchievements.ts" -Force
Remove-Item "hooks\shared\progress\useGameProgress.ts" -Force
Remove-Item "hooks\shared\progress\useProgressTracking.ts" -Force
Remove-Item "hooks\shared\ui\useGameEvents.ts" -Force
Remove-Item "hooks\shared\ui\useGameHints.ts" -Force
Remove-Item "hooks\shared\user\useUserProfile.ts" -Force
Remove-Item "lib\adapters\supabaseDataAdapter.ts" -Force
Remove-Item "lib\build-info.ts" -Force
Remove-Item "lib\constants\gameData\basic.ts" -Force
Remove-Item "lib\constants\gameData\lifestyle.ts" -Force
Remove-Item "lib\constants\gameData\special.ts" -Force
Remove-Item "lib\constants\gameData\world.ts" -Force
Remove-Item "lib\constants\gameHooksMap.ts" -Force
Remove-Item "lib\constants\gameItemsMap.ts" -Force
Remove-Item "lib\constants\ui\designTokens.ts" -Force
Remove-Item "lib\constants\ui\gameConfigs.ts" -Force
Remove-Item "lib\registry\gamesRegistry.ts" -Force
Remove-Item "lib\supabase\client.ts" -Force
Remove-Item "lib\types\components\buttons.ts" -Force
Remove-Item "lib\types\components\cards.ts" -Force
Remove-Item "lib\types\components\displays.ts" -Force
Remove-Item "lib\types\components\feedback.ts" -Force
Remove-Item "lib\types\components\game.ts" -Force
Remove-Item "lib\types\components\headers.ts" -Force
Remove-Item "lib\types\components\icons.ts" -Force
Remove-Item "lib\types\components\layout.ts" -Force
Remove-Item "lib\types\components\screens.ts" -Force
Remove-Item "lib\types\contexts\game-config.ts" -Force
Remove-Item "lib\types\contexts\game-type.ts" -Force
Remove-Item "lib\types\contexts\general.ts" -Force
Remove-Item "lib\types\contexts\simple-game-progress.ts" -Force
Remove-Item "lib\types\contexts\universal-game.ts" -Force
Remove-Item "lib\types\core\abstracts.ts" -Force
Remove-Item "lib\types\core\base.ts" -Force
Remove-Item "lib\types\core\functional.ts" -Force
Remove-Item "lib\types\events\game-events.ts" -Force
Remove-Item "lib\types\games\base.ts" -Force
Remove-Item "lib\types\games\items.ts" -Force
Remove-Item "lib\types\games\ui.ts" -Force
Remove-Item "lib\types\hooks\analytics.ts" -Force
Remove-Item "lib\types\hooks\game-state.ts" -Force
Remove-Item "lib\types\hooks\progress.ts" -Force
Remove-Item "lib\types\hooks\ui.ts" -Force
Remove-Item "lib\types\ui\core.ts" -Force
Remove-Item "lib\utils\errorUtils.ts" -Force
Remove-Item "lib\utils\game\gameMetadata.ts" -Force
Remove-Item "lib\utils\game\gameNavigation.ts" -Force
Remove-Item "lib\utils\game\gameUtils.ts" -Force
Remove-Item "lib\utils\speech\enhancedSpeechUtils.ts" -Force
Remove-Item "lib\utils.ts" -Force
Remove-Item "next-env.d.ts" -Force
Remove-Item "public\icons\HebrewIcons.tsx" -Force
Remove-Item "public\icons\ShapeIcons.tsx" -Force