import type { GameUIConfig } from '../gameUIConfig.types';

export const cultureWorldConfigs: Partial<Record<string, GameUIConfig>> = {
  "world-landmarks": {
    title: "🏙️ אתרים מפורסמים בעולם",
    subTitle: "זהה את האתר המפורסם של כל מדינה!",
    itemsTitle: "אתרים מפורסמים בעולם:",
    itemsDescription: "לחץ על האתר הנכון!",
    steps: [
      { icon: "🏙️", title: "1. תראה", description: "איזה אתר מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם האתר" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על האתר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #2d1b69 0%, #11998e 100%)",
      header: "text-white",
      subHeader: "text-teal-100",
      itemsDescription: "text-teal-100",
      button: { from: "teal", to: "cyan" },
      stepsBg: "bg-teal-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה אתר מפורסם זה?",
    challengeIcon: "🏙️🗺️✈️",
    challengeDescription: "זהה את האתר המפורסם ובחר את התשובה הנכונה!",
    itemLabel: "אתר",
    tip: "💡 טיפ: זכור את המדינה!",
    tipDescription: "כל אתר מפורסם קשור למדינה או עיר מסויימת",
    metadata: {
      keywords: "אתרים מפורסמים, פריז, אייפל, כותל, פירמידות, ניו יורק, גיל 7-12, גיאוגרפיה",
      description: "זהו אתרים מפורסמים בעולם! מגדל אייפל, הכותל המערבי, פירמידות ועוד — לגיל 7-12.",
    },
  },

  "solar-system": {
    title: "🪐 מערכת השמש",
    subTitle: "זהה כוכבי לכת וגרמי שמיים!",
    itemsTitle: "גרמי השמיים:",
    itemsDescription: "לחץ על גרם השמיים הנכון!",
    steps: [
      { icon: "🪐", title: "1. תראה", description: "איזה גרם שמיים מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את השם" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0d0d2b 0%, #1a1a6e 100%)",
      header: "text-yellow-200",
      subHeader: "text-indigo-200",
      itemsDescription: "text-indigo-200",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גרם שמיים זה?",
    challengeIcon: "🪐⭐🌌",
    challengeDescription: "זהה את גרם השמיים ובחר את התשובה הנכונה!",
    itemLabel: "גרם שמיים",
    tip: "💡 טיפ: שים לב לצבע ולגודל!",
    tipDescription: "לכל כוכב לכת צבע וגודל ייחודיים",
    metadata: {
      keywords: "מערכת השמש, כוכבי לכת, מאדים, שבתאי, נפטון, חלל, גיל 6-12, אסטרונומיה",
      description: "גלו את מערכת השמש! זהו כוכבי לכת לפי מראהם — אסטרונומיה לגיל 6-12.",
    },
  },

  "famous-paintings": {
    title: "🖼️ ציורים מפורסמים",
    subTitle: "זהה ציורים אגדיים מהיסטוריית האמנות!",
    itemsTitle: "ציורים מפורסמים:",
    itemsDescription: "לחץ על הציור הנכון!",
    steps: [
      { icon: "🖼️", title: "1. תראה", description: "איזה ציור מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הציור" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הציור הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #3d1c02 0%, #7b4f1e 100%)",
      header: "text-amber-100",
      subHeader: "text-amber-200",
      itemsDescription: "text-amber-200",
      button: { from: "amber", to: "orange" },
      stepsBg: "bg-amber-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה ציור מפורסם זה?",
    challengeIcon: "🖼️🎨🖌️",
    challengeDescription: "זהה את הציור המפורסם ובחר את התשובה הנכונה!",
    itemLabel: "ציור",
    tip: "💡 טיפ: זכור את הציירים הגדולים!",
    tipDescription: "כל ציור שייך לאמן גדול מהיסטוריית האמנות",
    metadata: {
      keywords: "ציורים מפורסמים, מונה ליזה, ון גוך, אמנות, גלריה, גיל 7-12, היסטוריית אמנות",
      description: "זהו ציורים מפורסמים מהיסטוריית האמנות! מונה ליזה, ון גוך ועוד — לגיל 7-12.",
    },
  },
};
