import type { GameUIConfig } from '../gameUIConfig.types';

export const geographyConfigs: Partial<Record<string, GameUIConfig>> = {
  'geography-flags': {
    title: '🚩 דגלי העולם',
    subTitle: 'לאיזו מדינה שייך הדגל?',
    itemsTitle: 'דגלי המדינות:',
    itemsDescription: 'לחץ על שם המדינה הנכונה!',
    steps: [
      { icon: '🚩', title: '1. תראה', description: 'איזה דגל מוצג?' },
      { icon: '🌍', title: '2. תזהה', description: 'לאיזו מדינה שייך הדגל?' },
      { icon: '👆', title: '3. תבחר', description: 'לחץ על שם המדינה הנכונה' },
    ],
    colors: {
      background: 'linear-gradient(135deg, #0d9488 0%, #0891b2 100%)',
      header: 'text-white',
      subHeader: 'text-teal-100',
      itemsDescription: 'text-teal-100',
      button: { from: 'teal', to: 'cyan' },
      stepsBg: 'bg-teal-100 bg-opacity-90',
    },
    grid: { className: 'grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto' },
    challengeTitle: 'לאיזו מדינה שייך הדגל הזה?',
    challengeIcon: '🚩',
    challengeDescription: 'זהה את הדגל ובחר את שם המדינה!',
    itemLabel: 'מדינה',
    tip: '💡 טיפ: שים לב לצבעים ולסמלים!',
    tipDescription: 'לכל דגל יש צבעים וסמלים ייחודיים שעוזרים לזהות את המדינה',
    metadata: {
      keywords: "דגלי מדינות, גאוגרפיה, מדינות עולם, ישראל, גיל 7-12, דגלים, מפה",
      description: "למדו לזהות דגלי מדינות! לאיזו מדינה שייך כל דגל — גאוגרפיה לגיל 7-12.",
    },
  },

  'geography-capitals': {
    title: '🏛️ בירות העולם',
    subTitle: 'מה הבירה של כל מדינה?',
    itemsTitle: 'מדינות ובירותיהן:',
    itemsDescription: 'לחץ על הבירה הנכונה!',
    steps: [
      { icon: '🚩', title: '1. תראה', description: 'איזו מדינה מוצגת?' },
      { icon: '🏛️', title: '2. תחשוב', description: 'מה הבירה של המדינה?' },
      { icon: '👆', title: '3. תבחר', description: 'לחץ על הבירה הנכונה' },
    ],
    colors: {
      background: 'linear-gradient(135deg, #0d9488 0%, #0891b2 100%)',
      header: 'text-white',
      subHeader: 'text-teal-100',
      itemsDescription: 'text-teal-100',
      button: { from: 'teal', to: 'cyan' },
      stepsBg: 'bg-teal-100 bg-opacity-90',
    },
    grid: { className: 'grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto' },
    challengeTitle: 'מה הבירה של המדינה?',
    challengeIcon: '🏛️',
    challengeDescription: 'ראה את הדגל ושם המדינה, ובחר את הבירה!',
    itemLabel: 'בירה',
    tip: '💡 טיפ: זכור בירות של מדינות מפורסמות!',
    tipDescription: 'כל מדינה יש לה בירה אחת — העיר הראשית שבה ממוקמת הממשלה',
    metadata: {
      keywords: "בירות עולם, ירושלים, פריז, לונדון, ברלין, גיל 8-13, גאוגרפיה, ערים",
      description: "למדו בירות העולם! מה הבירה של כל מדינה — גאוגרפיה מתקדמת לגיל 8-13.",
    },
  },

  'geography-continents': {
    title: '🌍 יבשות העולם',
    subTitle: 'באיזו יבשת נמצאת המדינה?',
    itemsTitle: 'מדינות ויבשותיהן:',
    itemsDescription: 'לחץ על היבשת הנכונה!',
    steps: [
      { icon: '🚩', title: '1. תראה', description: 'איזו מדינה מוצגת?' },
      { icon: '🌍', title: '2. תחשוב', description: 'באיזו יבשת היא נמצאת?' },
      { icon: '👆', title: '3. תבחר', description: 'לחץ על היבשת הנכונה' },
    ],
    colors: {
      background: 'linear-gradient(135deg, #0d9488 0%, #0891b2 100%)',
      header: 'text-white',
      subHeader: 'text-teal-100',
      itemsDescription: 'text-teal-100',
      button: { from: 'teal', to: 'cyan' },
      stepsBg: 'bg-teal-100 bg-opacity-90',
    },
    grid: { className: 'grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto' },
    challengeTitle: 'באיזו יבשת נמצאת המדינה?',
    challengeIcon: '🌍',
    challengeDescription: 'ראה את הדגל ושם המדינה, ובחר את היבשת!',
    itemLabel: 'יבשת',
    tip: '💡 טיפ: יש 5 יבשות עיקריות!',
    tipDescription: 'אירופה, אסיה, אמריקה, אפריקה ואוקיאניה',
    metadata: {
      keywords: "יבשות, אירופה, אסיה, אמריקה, אפריקה, אוקיאניה, גיל 8-13, גאוגרפיה",
      description: "למדו את יבשות העולם! באיזו יבשת נמצאת כל מדינה — גאוגרפיה לגיל 8-13.",
    },
  },
};
