import type { GameUIConfig } from '../gameUIConfig.types';

export const logosSportsConfigs: Partial<Record<string, GameUIConfig>> = {
  "flags": {
    title: "🌍 משחק דגלי מדינות",
    subTitle: "זהה את הדגל של כל מדינה!",
    itemsTitle: "מדינות העולם שלנו:",
    itemsDescription: "לחץ על המדינה הנכונה!",
    steps: [
      { icon: "🌍", title: "1. תראה", description: "איזה דגל מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם המדינה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על המדינה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "של איזו מדינה הדגל הזה?",
    challengeIcon: "🌍🗺️🌐",
    challengeDescription: "זהה את הדגל ובחר את התשובה הנכונה!",
    itemLabel: "מדינה",
    tip: "💡 טיפ: שים לב לצבעים!",
    tipDescription: "לכל דגל יש צבעים וסמלים ייחודיים שעוזרים לזהות את המדינה",
    metadata: {
      keywords: "דגלי מדינות, עולם, גאוגרפיה, מפה, מדינות, גיל 7-12, ידע כללי",
      description: "זהו דגלי מדינות מרחבי העולם! של איזו מדינה כל דגל — גאוגרפיה לגיל 7-12.",
    },
  },

  "soccer-logos": {
    title: "⚽ משחק סמלי כדורגל",
    subTitle: "זהה את הסמל של כל קבוצה!",
    itemsTitle: "קבוצות הכדורגל שלנו:",
    itemsDescription: "לחץ על הקבוצה הנכונה!",
    steps: [
      { icon: "⚽", title: "1. תראה", description: "איזה סמל מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הקבוצה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הקבוצה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1e3a5f 0%, #0d2137 50%, #0a1628 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "של איזו קבוצה הסמל הזה?",
    challengeIcon: "⚽🏆🥅",
    challengeDescription: "זהה את סמל הקבוצה ובחר את התשובה הנכונה!",
    itemLabel: "קבוצה",
    tip: "💡 טיפ: שים לב לצבעים ולסמל!",
    tipDescription: "לכל קבוצה יש סמל וצבעים ייחודיים",
    metadata: {
      keywords: "כדורגל, ליגות, ריאל מדריד, ברצלונה, מנצ'סטר, גיל 7-13, ספורט, לוגואים",
      description: "זהו סמלי קבוצות כדורגל מהעולם! ריאל מדריד, ברצלונה ועוד — לגיל 7-13.",
    },
  },

  "car-brands": {
    title: "🚗 לוגואים של מכוניות",
    subTitle: "זהה את הלוגו של כל מותג!",
    itemsTitle: "מותגי המכוניות שלנו:",
    itemsDescription: "לחץ על המותג הנכון!",
    steps: [
      { icon: "🚗", title: "1. תראה", description: "איזה לוגו מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם המותג" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על המותג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזה מותג הלוגו הזה?",
    challengeIcon: "🚗🏎️🚙",
    challengeDescription: "זהה את לוגו המכונית ובחר את התשובה הנכונה!",
    itemLabel: "מותג",
    tip: "💡 טיפ: שים לב לצורת הלוגו!",
    tipDescription: "לכל מותג יש צורה וסימן ייחודיים שעוזרים לזהות אותו",
    metadata: {
      keywords: "מותגי מכוניות, BMW, אאודי, טויוטה, פורד, לוגואים, גיל 7-13, תחבורה",
      description: "זהו לוגואים של מותגי מכוניות מפורסמים! BMW, טויוטה, פורד ועוד — לגיל 7-13.",
    },
  },

  "tech-logos": {
    title: "📱 לוגואים של טכנולוגיה",
    subTitle: "זהה לוגואים של חברות הטכנולוגיה הגדולות!",
    itemsTitle: "חברות טכנולוגיה:",
    itemsDescription: "לחץ על הלוגו הנכון!",
    steps: [
      { icon: "📱", title: "1. תראה", description: "איזה לוגו מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם החברה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הלוגו הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0369a1 0%, #1e3a5f 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "blue" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזו חברה זה הלוגו?",
    challengeIcon: "📱💻🌐",
    challengeDescription: "זהה את הלוגו של חברת הטכנולוגיה ובחר את התשובה הנכונה!",
    itemLabel: "חברה",
    tip: "💡 טיפ: שים לב לצורה ולצבע!",
    tipDescription: "לכל חברת טכנולוגיה יש לוגו ייחודי שקל לזהות",
    metadata: {
      keywords: "חברות טכנולוגיה, אפל, גוגל, מטא, מיקרוסופט, לוגואים, גיל 8-13, טק",
      description: "זהו לוגואים של חברות טכנולוגיה ענקיות! אפל, גוגל, מטא ועוד — לגיל 8-13.",
    },
  },

  "nba-teams": {
    title: "🏀 קבוצות NBA",
    subTitle: "זהה לוגואים של קבוצות הכדורסל הגדולות!",
    itemsTitle: "קבוצות NBA:",
    itemsDescription: "לחץ על הלוגו הנכון!",
    steps: [
      { icon: "🏀", title: "1. תראה", description: "של איזה קבוצה הלוגו?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הקבוצה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הלוגו הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #7c2d12 0%, #c2410c 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזו קבוצת NBA זה הלוגו?",
    challengeIcon: "🏀🏆🌟",
    challengeDescription: "זהה את לוגו קבוצת ה-NBA ובחר את התשובה הנכונה!",
    itemLabel: "קבוצה",
    tip: "💡 טיפ: זכור את הצבעים של כל קבוצה!",
    tipDescription: "לכל קבוצת NBA צבעים וסמל ייחודיים",
    metadata: {
      keywords: "NBA, כדורסל, לייקרס, בולס, גולדן סטייט, לוגואים, גיל 8-13, ספורט",
      description: "זהו לוגואים של קבוצות NBA! לייקרס, בולס, גולדן סטייט ועוד — לגיל 8-13.",
    },
  },
};
