import type { GameUIConfig } from '../gameUIConfig.types';

export const natureAnimalsConfigs: Partial<Record<string, GameUIConfig>> = {
  "dog-breeds": {
    title: "🐕 גזעי כלבים",
    subTitle: "זהה גזעי כלבים מסביב לעולם!",
    itemsTitle: "גזעי כלבים:",
    itemsDescription: "לחץ על הכלב הנכון!",
    steps: [
      { icon: "🐕", title: "1. תראה", description: "איזה גזע כלב מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הגזע" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הכלב הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #92400e 0%, #d97706 100%)",
      header: "text-white",
      subHeader: "text-amber-100",
      itemsDescription: "text-amber-100",
      button: { from: "amber", to: "yellow" },
      stepsBg: "bg-amber-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גזע כלב זה?",
    challengeIcon: "🐕🦴🐾",
    challengeDescription: "זהה את גזע הכלב ובחר את התשובה הנכונה!",
    itemLabel: "גזע כלב",
    tip: "💡 טיפ: שים לב לגודל ולצורת הגוף!",
    tipDescription: "לכל גזע כלב מראה וגוף ייחודיים",
  },

  "cat-breeds": {
    title: "🐱 גזעי חתולים",
    subTitle: "זהה גזעי חתולים מסביב לעולם!",
    itemsTitle: "גזעי חתולים:",
    itemsDescription: "לחץ על החתול הנכון!",
    steps: [
      { icon: "🐱", title: "1. תראה", description: "איזה גזע חתול מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הגזע" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על החתול הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #4c1d95 0%, #6d28d9 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "violet" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גזע חתול זה?",
    challengeIcon: "🐱😺🐾",
    challengeDescription: "זהה את גזע החתול ובחר את התשובה הנכונה!",
    itemLabel: "גזע חתול",
    tip: "💡 טיפ: שים לב לצורת הפנים ולפרווה!",
    tipDescription: "לכל גזע חתול מראה פרווה וגוף ייחודיים",
  },

  "exotic-birds": {
    title: "🦩 ציפורים אקזוטיות",
    subTitle: "זהה ציפורים מפורסמות מסביב העולם!",
    itemsTitle: "ציפורים אקזוטיות:",
    itemsDescription: "לחץ על הציפור הנכון!",
    steps: [
      { icon: "🦩", title: "1. תראה", description: "איזו ציפור מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הציפור" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "cyan" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזו ציפור זה?",
    challengeIcon: "🦩🦥🦜",
    challengeDescription: "זהה את הציפור ובחר את התשובה הנכונה!",
    itemLabel: "ציפור",
    tip: "💡 טיפ: שים לב לצבע ולצורת הגוף!",
    tipDescription: "לכל ציפור צבעים ותכונות ייחודיות",
  },

  "butterflies": {
    title: "🦋 פרפרים",
    subTitle: "זהה פרפרים צבעוניים מסביב העולם!",
    itemsTitle: "פרפרים:",
    itemsDescription: "לחץ על הפרפר הנכון!",
    steps: [
      { icon: "🦋", title: "1. תראה", description: "איזה פרפר מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הפרפר" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #831843 0%, #ec4899 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "rose" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה פרפר זה?",
    challengeIcon: "🦋🌸🌿",
    challengeDescription: "זהה את הפרפר ובחר את התשובה הנכונה!",
    itemLabel: "פרפר",
    tip: "💡 טיפ: שים לב לצבע ולצורת הכנפיים!",
    tipDescription: "לכל פרפר כנפיים בצבעים ודוגמאות ייחודיים",
  },
};
