import type { GameUIConfig } from '../gameUIConfig.types';

export const coreLearningConfigs: Partial<Record<string, GameUIConfig>> = {
  colors: {
    title: "🎨 משחק צבעים 🎨",
    subTitle: "למד צבעים דרך משחק!",
    itemsTitle: "הצבעים שנלמד:",
    itemsDescription: "לחץ על צבע כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה צבע אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם הצבע" },
      { icon: "👆", title: "3. תלחץ", description: "על הצבע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 25%, #a8e6cf 50%, #dcedc1 75%, #ffd3e1 100%)",
      header: "text-purple-800",
      subHeader: "text-purple-600",
      itemsDescription: "text-gray-100",
      button: { from: "teal", to: "cyan" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה צבע שמעת?",
    challengeIcon: "🎨🌈🖍️🎪",
    challengeDescription: "בחר את הצבע הנכון!",
    itemLabel: "צבע",
    tip: "💡 טיפ: תשמע את שם הצבע!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצבעים למטה לשמוע את השמות",
    // 🔍 מטאדאטה SEO
    metadata: {
      keywords: "משחק צבעים לילדים, למידת צבעים, משחקים חינוכיים, גיל 2-10, פעוטות, צבעים בעברית",
      description: "משחק אינטראקטיבי ללימוד צבעים לילדים בגילאי 2-10. למדו צבעים בעברית דרך משחק מהנה וחינוכי!",
    },
  },

  letters: {
    title: "🔤 משחק אותיות 📝",
    subTitle: "למד אותיות דרך שמיעה!",
    itemsTitle: "האותיות שנלמד:",
    itemsDescription: "לחץ על אות כדי לשמוע את השם שלה!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזו אות אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך נראית האות" },
      { icon: "👆", title: "3. תלחץ", description: "על האות הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fed7aa 0%, #fdba74 25%, #fb923c 50%, #f97316 75%, #ea580c 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "yellow", to: "orange" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-4 md:grid-cols-6 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזו אות שמעת?",
    challengeIcon: "🔤📝✏️📄",
    challengeDescription: "בחר את האות הנכונה!",
    itemLabel: "אות",
    tip: "💡 טיפ: תשמע את שם האות!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על האותיות למטה לשמוע את השמות",
    metadata: {
      keywords: "משחק אותיות לילדים, אלפבית עברי, לימוד אותיות, גיל 4-7, עברית, א ב ג",
      description: "משחק אינטראקטיבי ללימוד כל 22 אותיות האלפבית העברי לילדים בגיל 4-7. שמעו את שם האות ובחרו נכון!",
    },
  },

  "hebrew-script": {
    title: "✍️ כתב עברי — זיהוי אותיות כתב",
    subTitle: "למד לזהות את אותיות הכתב העברי!",
    itemsTitle: "האותיות שנלמד:",
    itemsDescription: "לחץ על אות כדי לשמוע את שמה!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "שם האות בעברית" },
      { icon: "🤔", title: "2. תחשוב", description: "איך האות נראית בכתב" },
      { icon: "👆", title: "3. תלחץ", description: "על האות הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 50%, #c3cfe2 100%)",
      header: "text-indigo-900",
      subHeader: "text-indigo-700",
      itemsDescription: "text-indigo-100",
      button: { from: "indigo", to: "violet" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-4 md:grid-cols-6 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    challengeTitle: "איזו אות שמעת?",
    challengeIcon: "✍️📝🖊️",
    challengeDescription: "בחר את האות הנכונה!",
    itemLabel: "אות",
    tip: "💡 טיפ: תשמע היטב את שם האות!",
    tipDescription: "לחץ על הסמל כדי לשמוע שוב את שם האות",
    metadata: {
      keywords: "כתב עברי, אותיות כתב, זיהוי אותיות, כיתה א, גן חובה, כתב סת\"ם",
      description: "משחק ללימוד זיהוי אותיות הכתב העברי — כולל 22 אותיות ו-5 אותיות סופיות. מתאים לגיל 6-8.",
    },
  },

  shapes: {
    title: "🔺 משחק צורות 🟡",
    subTitle: "למד צורות דרך שמיעה!",
    itemsTitle: "הצורות שנלמד:",
    itemsDescription: "לחץ על צורה כדי לשמוע את השם שלה!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזו צורה אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך נראית הצורה" },
      { icon: "👆", title: "3. תלחץ", description: "על הצורה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #d4f1d4 0%, #a8e6a8 25%, #7dd87d 50%, #52c952 75%, #26b926 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "blue", to: "green" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-6 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזו צורה שמעת?",
    challengeIcon: "🔺🟡⭐💎",
    challengeDescription: "בחר את הצורה הנכונה!",
    itemLabel: "צורה",
    tip: "💡 טיפ: תשמע את שם הצורה!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצורות למטה לשמוע את השמות",
    metadata: {
      keywords: "משחק צורות לילדים, לימוד צורות, גאומטריה לפעוטות, גיל 3-7, עיגול, ריבוע, משולש",
      description: "משחק אינטראקטיבי ללימוד צורות גאומטריות לילדים בגיל 3-7. שמעו את שם הצורה ומצאו אותה!",
    },
  },

  "colored-shapes": {
    title: "🔴🔺 משחק צורות צבעוניות 🟡🟦",
    subTitle: "למד צורות וצבעים יחד!",
    itemsTitle: "הצורות הצבעוניות שנלמד:",
    itemsDescription: "לחץ על צורה צבעונית כדי לשמוע את השם שלה!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזו צורה באיזה צבע אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך נראית הצורה הצבעונית" },
      { icon: "👆", title: "3. תלחץ", description: "על הצורה הצבעונית הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 25%, #a8e6cf 50%, #dcedc1 75%, #d4f1d4 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "teal", to: "green" },
      stepsBg: "bg-gradient-to-r from-orange-100 to-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 max-w-6xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזו צורה צבעונית שמעת?",
    challengeIcon: "🔴🔺🟡⭐🔵💎",
    challengeDescription: "בחר את הצורה בצבע הנכון!",
    itemLabel: "צורה צבעונית",
    tip: "💡 טיפ: תשמע את שם הצורה והצבע יחד!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצורות למטה לשמוע את השמות",
    metadata: {
      keywords: "צורות צבעוניות, גאומטריה, צבעים וצורות, גיל 3-7, לימוד צורות, לימוד צבעים",
      description: "למדו צורות וצבעים יחד! משחק משולב שמזהה צורה גאומטרית עם הצבע שלה לגיל 3-7.",
    },
  },

  numbers: {
    title: "🔢 משחק מספרים 🎯",
    subTitle: "למד מספרים דרך שמיעה!",
    itemsTitle: "המספרים שנלמד:",
    itemsDescription: "לחץ על מספר כדי לשמוע אותו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מספר אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך נראה המספר" },
      { icon: "👆", title: "3. תלחץ", description: "על המספר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #e0e7ff 0%, #c7d2fe 25%, #a5b4fc 50%, #818cf8 75%, #6366f1 100%)",
      header: "text-white",
      subHeader: "text-indigo-100",
      itemsDescription: "text-indigo-100",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-4 md:grid-cols-5 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה מספר שמעת?",
    challengeIcon: "🔢🎯123️⃣",
    challengeDescription: "בחר את המספר הנכון!",
    itemLabel: "מספר",
    tip: "💡 טיפ: תשמע את המספר!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המספרים למטה לשמוע אותם",
    metadata: {
      keywords: "משחק מספרים לילדים, לימוד מספרים, ספירה, גיל 3-7, עברית, מתמטיקה לפעוטות",
      description: "משחק אינטראקטיבי ללימוד מספרים 1-20 לילדים בגיל 3-7. שמעו מספר ובחרו את הכרטיס הנכון!",
    },
  },

  'days-of-week': {
    title: "📅 ימות השבוע",
    subTitle: "למד את ימות השבוע בעברית!",
    itemsTitle: "ימות השבוע:",
    itemsDescription: "לחץ על יום כדי לשמוע את שמו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה יום קוראים" },
      { icon: "🤔", title: "2. תחשוב", description: "איזה יום זה?" },
      { icon: "👆", title: "3. תלחץ", description: "על היום הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
      header: "text-blue-800",
      subHeader: "text-blue-600",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "cyan" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-4 gap-4" },
    challengeTitle: "איזה יום שמעת?",
    challengeIcon: "📅🗓️☀️",
    challengeDescription: "בחר את יום השבוע הנכון!",
    itemLabel: "יום",
    tip: "💡 טיפ: תשמע את שם היום!",
    tipDescription: "ישנם 7 ימות השבוע — מיום ראשון עד שבת",
    metadata: {
      keywords: "ימות השבוע, ראשון שני שלישי, לוח שנה, גיל 4-7, לימוד זמן, עברית",
      description: "למדו את 7 ימות השבוע בעברית! ראשון, שני, שלישי... עד שבת — משחק חינוכי לגיל 4-7.",
    },
  },

  'visual-opposites': {
    title: "🔄 ניגודים",
    subTitle: "מה ההפך? — למד מושגי ניגוד!",
    itemsTitle: "מושגי ניגוד:",
    itemsDescription: "לחץ על מושג כדי לשמוע אותו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מושג אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "מה המשמעות?" },
      { icon: "👆", title: "3. תלחץ", description: "על המושג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)",
      header: "text-purple-900",
      subHeader: "text-purple-700",
      itemsDescription: "text-purple-900",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-4 gap-4" },
    challengeTitle: "איזה מושג שמעת?",
    challengeIcon: "🔄↔️⬆️⬇️",
    challengeDescription: "בחר את הניגוד הנכון!",
    itemLabel: "מושג",
    tip: "💡 טיפ: כל מילה יש לה הפך!",
    tipDescription: "גדול ↔ קטן, חם ↔ קר, מהיר ↔ איטי",
    metadata: {
      keywords: "ניגודים, מושגי ניגוד, הפכים, גדול קטן, גיל 3-7, שפה עברית, מושגים בסיסיים",
      description: "למדו הפכים ומושגי ניגוד בעברית! גדול/קטן, חם/קר, מהיר/איטי — מרחיב אוצר מילים לגיל 3-7.",
    },
  },

  'english-cards': {
    title: "🔤 אנגלית ראשונה",
    subTitle: "שמע מילה אנגלית ובחר את התמונה הנכונה!",
    itemsTitle: "מילים באנגלית:",
    itemsDescription: "לחץ על מילה כדי לשמוע אותה!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "מילה באנגלית" },
      { icon: "🤔", title: "2. תחשוב", description: "מה היא אומרת?" },
      { icon: "👆", title: "3. תלחץ", description: "על התמונה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      header: "text-white",
      subHeader: "text-indigo-100",
      itemsDescription: "text-indigo-100",
      button: { from: "indigo", to: "violet" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-5 gap-4" },
    challengeTitle: "איזו מילה שמעת?",
    challengeIcon: "🔤🇬🇧📖✨",
    challengeDescription: "בחר את התמונה הנכונה!",
    itemLabel: "מילה",
    tip: "💡 טיפ: תשמע את המילה האנגלית!",
    tipDescription: "אנגלית היא שפה חשובה מאוד ללמוד",
    metadata: {
      keywords: "אנגלית ראשונה, מילים באנגלית, לימוד אנגלית, גיל 4-7, שפה שניה, אנגלית לפעוטות",
      description: "שמעו מילה באנגלית ובחרו את התמונה הנכונה! לימוד מילים ראשונות באנגלית לגיל 4-7.",
    },
  },

  'spatial-concepts': {
    title: "🗺️ מושגי מרחב",
    subTitle: "למד מושגי מיקום בעברית!",
    itemsTitle: "מושגי מרחב:",
    itemsDescription: "לחץ על מושג כדי לשמוע אותו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מושג אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "מה המשמעות?" },
      { icon: "👆", title: "3. תלחץ", description: "על המושג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #d4fc79 0%, #96e6a1 100%)",
      header: "text-green-800",
      subHeader: "text-green-700",
      itemsDescription: "text-green-800",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-5 gap-4" },
    challengeTitle: "איזה מושג מרחב שמעת?",
    challengeIcon: "⬆️⬇️↔️📦",
    challengeDescription: "בחר את מושג המרחב הנכון!",
    itemLabel: "מושג",
    tip: "💡 טיפ: שים לב לכיוון!",
    tipDescription: "מושגי מרחב עוזרים לנו לתאר היכן נמצאים עצמים",
    metadata: {
      keywords: "מושגי מרחב, למעלה למטה, שמאל ימין, מיקום, גיל 3-6, חינוך מרחבי, כיוונים",
      description: "למדו מושגי מרחב ומיקום — למעלה/למטה, שמאל/ימין, לפנים/מאחור! חיוני לגיל 3-6.",
    },
  },

  'number-words': {
    title: "🔢 מספרים כמילים",
    subTitle: "למד לקרוא מספרים בעברית!",
    itemsTitle: "המספרים:",
    itemsDescription: "לחץ על מספר כדי לשמוע אותו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מספר אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "מה המספר?" },
      { icon: "👆", title: "3. תלחץ", description: "על המספר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
      header: "text-orange-800",
      subHeader: "text-orange-700",
      itemsDescription: "text-orange-800",
      button: { from: "orange", to: "amber" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-3 md:grid-cols-7 gap-3" },
    challengeTitle: "איזה מספר שמעת?",
    challengeIcon: "1️⃣2️⃣3️⃣🔢",
    challengeDescription: "בחר את המספר הנכון!",
    itemLabel: "מספר",
    tip: "💡 טיפ: שמע את שם המספר בעברית!",
    tipDescription: "בעברית כותבים מספרים כמילים — אחד, שתיים, שלוש...",
    metadata: {
      keywords: "מספרים כמילים, אחד שתיים שלוש, לימוד מספרים, גיל 5-8, כתיבת מספרים, עברית",
      description: "למדו לקרוא ולכתוב מספרים כמילים בעברית — אחד, שתיים, שלוש... עד עשרה ומעבר לזה!",
    },
  },

  'months-of-year': {
    title: "🗓️ חודשי השנה",
    subTitle: "למד את חודשי השנה בעברית!",
    itemsTitle: "חודשי השנה:",
    itemsDescription: "לחץ על חודש כדי לשמוע את שמו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה חודש קוראים" },
      { icon: "🤔", title: "2. תחשוב", description: "איזה חודש זה?" },
      { icon: "👆", title: "3. תלחץ", description: "על החודש הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)",
      header: "text-purple-800",
      subHeader: "text-purple-600",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-4" },
    challengeTitle: "איזה חודש שמעת?",
    challengeIcon: "🗓️📆🌸",
    challengeDescription: "בחר את חודש השנה הנכון!",
    itemLabel: "חודש",
    tip: "💡 טיפ: תשמע את שם החודש!",
    tipDescription: "ישנם 12 חודשים בשנה — מינואר עד דצמבר",
    metadata: {
      keywords: "חודשי השנה, ינואר פברואר מרץ, לוח שנה, גיל 4-7, לימוד זמן, עברית",
      description: "למדו את 12 חודשי השנה בעברית! ינואר עד דצמבר — משחק חינוכי מהנה לגיל 4-7.",
    },
  },
};
