import {
  Bird,
  Waves,
  Bone,
  Apple,
  Shield,
  Hammer,
  Box,
  Sparkles,
  Gamepad2,
  Flame,
  Car,
  Paintbrush,
  Zap,
  Music,
  Lightbulb,
  Calculator,
  Hash,
  BookOpen,
} from "lucide-react";
import type { GameRegistration } from "@/lib/types/games/base";

export const gamesRegistryBatch3: GameRegistration[] = [
  // משחקי ארקייד
  { id: "flappy-bird",      title: "ציפור מעופפת",                  description: "עזור לציפור לעבור בין הצינורות!",                    icon: Bird,           emoji: "🐦", color: "bg-sky-400 hover:bg-sky-500",                                                                           href: "/games/flappy-bird",     available: true, order: 96,  ageMin: 5 },
  { id: "snake",            title: "נחש",                           description: "אסוף פירות וגדל — אל תפגע בקירות!",                 icon: Waves,          emoji: "🐍", color: "bg-emerald-500 hover:bg-emerald-600",                                                                   href: "/games/snake",           available: true, order: 97,  ageMin: 6 },
  { id: "dino-runner",      title: "דינוזאור קופץ",                 description: "קפוץ מעל המכשולים והגע רחוק!",                      icon: Bone,           emoji: "🦖", color: "bg-amber-500 hover:bg-amber-600",                                                                       href: "/games/dino-runner",     available: true, order: 98,  ageMin: 5 },
  { id: "catch-fruit",      title: "תפוס פירות",                    description: "הזז את הסל ותפוס פירות — הימנע מהפצצות!",           icon: Apple,          emoji: "🧺", color: "bg-purple-500 hover:bg-purple-600",                                                                     href: "/games/catch-fruit",     available: true, order: 99,  ageMin: 4 },
  { id: "space-defender",   title: "מגן החלל",                      description: "ירה באסטרואידים והגן על כדור הארץ!",                icon: Shield,         emoji: "🚀", color: "bg-indigo-600 hover:bg-indigo-700",                                                                     href: "/games/space-defender",  available: true, order: 100, ageMin: 6 },
  { id: "whack-a-mole",     title: "חבט על החפרפרת",                description: "חבט על החפרפרות לפני שהן נעלמות — אל תחבוט על הפצצות!", icon: Hammer,    emoji: "🔨", color: "bg-amber-500 hover:bg-amber-600",                                                                       href: "/games/whack-a-mole",    available: true, order: 101, ageMin: 4 },
  { id: "brick-breaker",    title: "שובר לבנים",                    description: "שבר את כל הלבנים עם הכדור לפני שאוזל החיים!",      icon: Box,            emoji: "🧱", color: "bg-purple-600 hover:bg-purple-700",                                                                     href: "/games/brick-breaker",   available: true, order: 102, ageMin: 6 },
  { id: "balloon-pop",      title: "פוצץ בלונים",                   description: "פוצץ בלונים לפני שהם בורחים — הישמר מהפצצות!",     icon: Sparkles,       emoji: "🎈", color: "bg-pink-500 hover:bg-pink-600",                                                                         href: "/games/balloon-pop",     available: true, order: 103, ageMin: 4 },
  { id: "pong",             title: "פונג",                          description: "שחק פונג קלאסי מול המחשב — ראשון ל-7 נקודות מנצח!", icon: Gamepad2,      emoji: "🏓", color: "bg-slate-600 hover:bg-slate-700",                                                                       href: "/games/pong",            available: true, order: 104, ageMin: 6 },
  { id: "meteor-dodge",     title: "התחמק ממטאורים",                description: "הזז את הספינה והתחמק ממטאורים נופלים — אסוף כוכבים!", icon: Flame,       emoji: "☄️", color: "bg-orange-600 hover:bg-orange-700",                                                                     href: "/games/meteor-dodge",    available: true, order: 105, ageMin: 6 },
  { id: "frogger",          title: "צפרדע חוצה",                    description: "עזור לצפרדע לחצות את הכביש — הימנע מהרכבים!",      icon: Car,            emoji: "🐸", color: "bg-green-600 hover:bg-green-700",                                                                       href: "/games/frogger",         available: true, order: 106, ageMin: 6 },
  { id: "stack",            title: "ערם לבנים",                     description: "הפל לבנים בזמן הנכון ובנה מגדל גבוה!",             icon: Box,            emoji: "🏗️", color: "bg-blue-600 hover:bg-blue-700",                                                                         href: "/games/stack",           available: true, order: 107, ageMin: 5 },
  { id: "color-tap",        title: "צבע נכון",                      description: "לחץ על הצבע הנכון לפני שהזמן יגמר!",               icon: Paintbrush,     emoji: "🎨", color: "bg-pink-500 hover:bg-pink-600",                                                                         href: "/games/color-tap",       available: true, order: 108, ageMin: 4 },
  { id: "jumper",           title: "קפצן",                          description: "קפץ על הפלטפורמות וטפס גבוה ככל האפשר!",           icon: Zap,            emoji: "🦘", color: "bg-indigo-500 hover:bg-indigo-600",                                                                     href: "/games/jumper",          available: true, order: 109, ageMin: 5 },
  { id: "simon",            title: "שיימון אומר",                   description: "זכור את סדר הצבעים וחזור עליהם!",                  icon: Music,          emoji: "🔴", color: "bg-gray-700 hover:bg-gray-800",                                                                         href: "/games/simon",           available: true, order: 110, ageMin: 5 },
  // משחקים חינוכיים חדשים
  { id: "true-false",       title: "נכון או לא נכון",               description: "ענה נכון/לא נכון על עובדות מעניינות!",             icon: Lightbulb,      emoji: "✅", color: "bg-teal-500 hover:bg-teal-600",                                                                         href: "/games/true-false",      available: true, order: 111, ageMin: 5, contentType: 'riddle' as const },
  { id: "emoji-math",       title: "מתמטיקה עם אמוג׳י",             description: "ספור אמוג׳י ופתור תרגילי חיבור וחיסור!",           icon: Calculator,     emoji: "🧮", color: "bg-yellow-500 hover:bg-yellow-600",                                                                     href: "/games/emoji-math",      available: true, order: 112, ageMin: 4 },
  { id: "math-race",        title: "מרוץ מתמטיקה",                  description: "פתור כמה שיותר תרגילים ב-30 שניות!",               icon: Zap,            emoji: "🏎️", color: "bg-blue-500 hover:bg-blue-600",                                                                         href: "/games/math-race",       available: true, order: 113, ageMin: 6 },
  { id: "number-bubbles",   title: "בועות מספרים",                  description: "פוצץ את הבועות לפי הסדר: 1, 2, 3!",               icon: Hash,           emoji: "🫧", color: "bg-purple-500 hover:bg-purple-600",                                                                     href: "/games/number-bubbles",  available: true, order: 114, ageMin: 4 },
  { id: "word-scramble",    title: "מילים מבולבלות",                 description: "סדר את האותיות ליצירת המילה הנכונה!",              icon: BookOpen,       emoji: "🔡", color: "bg-green-500 hover:bg-green-600",                                                                       href: "/games/word-scramble",   available: true, order: 115, ageMin: 6, contentType: 'riddle' as const },
];
