import {
  Heart,
  Circle,
  Square,
  Hash,
  Apple,
  Music,
  Cloud,
  Calculator,
  User,
  Salad,
  Sparkles,
  Shirt,
  Coffee,
  Home,
  Wrench,
  Puzzle,
  Paintbrush,
  Palette,
  Building,
  Layers,
  Trophy,
  ChefHat,
  Hand,
  Bone,
  Utensils,
  Recycle,
  Pill,
  Volume2,
  Calendar,
  ShoppingCart,
  Shield,
  Waves,
  Flower,
  PartyPopper,
  Cpu,
  Briefcase,
  CloudRain,
  Rainbow,
  Star,
} from "lucide-react";
import { HebrewLettersIcon } from "@/components/icons/HebrewIcons";
import type { GameRegistration } from "@/lib/types/games/base";

export const gamesRegistryBatch1: GameRegistration[] = [
  { id: "memory",          title: "משחק זיכרון",                    description: "מצא את הזוגות!",                                          icon: Heart,          emoji: "🧠", color: "bg-pink-400 hover:bg-pink-500",                                                                              href: "/games/memory",          available: true, order: 1 },
  { id: "colors",          title: "משחק צבעים",                     description: "למד צבעים!",                                               icon: Circle,         emoji: "🌈", color: "bg-blue-400 hover:bg-blue-500",                                                                              href: "/games/colors",          available: true, order: 2 },
  { id: "letters",         title: "משחק אותיות",                    description: "למד אותיות!",                                              icon: HebrewLettersIcon, emoji: "א", color: "bg-orange-400 hover:bg-orange-500",                                                                       href: "/games/letters",         available: true, order: 3 },
  { id: "hebrew-letters",  title: "תרגול כתיבה בעברית",             description: "תרגל כתיבת כל האותיות!",                                  icon: HebrewLettersIcon, emoji: "✍️", color: "bg-green-400 hover:bg-green-500",                                                                        href: "/games/hebrew-letters",  available: true, order: 3.5 },
  { id: "shapes",          title: "משחק צורות",                     description: "למד צורות!",                                               icon: Square,         emoji: "🔷", color: "bg-green-400 hover:bg-green-500",                                                                            href: "/games/shapes",          available: true, order: 4 },
  { id: "colored-shapes",  title: "משחק צורות צבעוניות",            description: "בחר צורה בצבע הנכון!",                                    icon: Circle,         emoji: "🟡", color: "bg-gradient-to-r from-orange-400 to-green-400 hover:from-orange-500 hover:to-green-500",                href: "/games/colored-shapes",  available: true, order: 4.5 },
  { id: "numbers",         title: "משחק מספרים",                    description: "למד מספרים!",                                              icon: Hash,           emoji: "🔢", color: "bg-indigo-400 hover:bg-indigo-500",                                                                          href: "/games/numbers",         available: true, order: 5 },
  { id: "fruits",          title: "משחק פירות",                     description: "למד פירות!",                                               icon: Apple,          emoji: "🍎", color: "bg-red-400 hover:bg-red-500",                                                                               href: "/games/fruits",          available: true, order: 6 },
  { id: "bubbles",         title: "בועות מוזיקליות",                 description: "פוצץ בועות ושמע צלילים!",                                 icon: Music,          emoji: "🎵", color: "bg-blue-400 hover:bg-blue-500",                                                                             href: "/games/bubbles",         available: true, order: 8 },
  { id: "counting",        title: "משחק ספירה",                     description: "ספור אימוג'ים!",                                           icon: Hash,           emoji: "🔟", color: "bg-cyan-400 hover:bg-cyan-500",                                                                             href: "/games/counting",        available: true, order: 9 },
  { id: "weather",         title: "משחק מזג אוויר",                 description: "למד על מזג האוויר!",                                      icon: Cloud,          emoji: "⛅", color: "bg-sky-400 hover:bg-sky-500",                                                                               href: "/games/weather",         available: true, order: 10 },
  { id: "math",            title: "משחק חשבון",                     description: "למד חיבור וחיסור!",                                       icon: Calculator,     emoji: "➕", color: "bg-yellow-400 hover:bg-yellow-500",                                                                         href: "/games/math",            available: true, order: 12 },
  { id: "professions",     title: "משחק מקצועות",                   description: "למד על מקצועות שונים!",                                   icon: User,           emoji: "👩‍⚕️", color: "bg-purple-400 hover:bg-purple-500",                                                                     href: "/games/professions",     available: true, order: 13 },
  { id: "vegetables",      title: "משחק ירקות",                     description: "למד ירקות בריאים!",                                       icon: Salad,          emoji: "🥦", color: "bg-green-400 hover:bg-green-500",                                                                           href: "/games/vegetables",      available: true, order: 14 },
  { id: "space",           title: "משחק גופי השמים",                description: "חקור את החלל והכוכבים!",                                  icon: Sparkles,       emoji: "🌟", color: "bg-indigo-400 hover:bg-indigo-500",                                                                         href: "/games/space",           available: true, order: 16 },
  { id: "clothing",        title: "משחק בגדים ואביזרים",            description: "למד על פריטי לבוש שונים!",                                icon: Shirt,          emoji: "👗", color: "bg-pink-400 hover:bg-pink-500",                                                                             href: "/games/clothing",        available: true, order: 17 },
  { id: "smells-tastes",   title: "משחק ריחות וטעמים",              description: "זהה ריחות וטעמים שונים!",                                 icon: Coffee,         emoji: "👃", color: "bg-amber-400 hover:bg-amber-500",                                                                           href: "/games/smells-tastes",   available: true, order: 18 },
  { id: "house",           title: "משחק חפצי הבית",                 description: "למד חפצים בבית!",                                         icon: Home,           emoji: "🏠", color: "bg-sky-400 hover:bg-sky-500",                                                                               href: "/games/house",           available: true, order: 19 },
  { id: "tools",           title: "משחק כלי עבודה",                 description: "למד כלי עבודה שונים!",                                    icon: Wrench,         emoji: "🔧", color: "bg-orange-400 hover:bg-orange-500",                                                                         href: "/games/tools",           available: true, order: 20 },
  { id: "tzedakah",        title: "משחק קופת הצדקה",                description: "תפוס מטבעות לצדקה!",                                     icon: Heart,          emoji: "🪙", color: "bg-pink-400 hover:bg-pink-500",                                                                             href: "/games/tzedakah",        available: true, order: 22 },
  { id: "puzzles",         title: "משחק פאזלים",                    description: "הרכב תמונות יפות!",                                       icon: Puzzle,         emoji: "🧩", color: "bg-purple-400 hover:bg-purple-500",                                                                         href: "/games/puzzles",         available: true, order: 23 },
  { id: "drawing",         title: "משחק ציורים",                    description: "צייר יצירות אמנות!",                                      icon: Paintbrush,     emoji: "✏️", color: "bg-orange-400 hover:bg-orange-500",                                                                         href: "/games/drawing",         available: true, order: 24 },
  { id: "coloring",        title: "צביעת תמונות",                   description: "בחר צבע וצבע ציורים מהנים!",                              icon: Palette,        emoji: "🎨", color: "bg-gradient-to-r from-pink-400 to-purple-400 hover:from-pink-500 hover:to-purple-500",               href: "/games/coloring",        available: true, order: 24.5 },
  { id: "building",        title: "סטודיו הבנייה הקסום",            description: "בנה יצירות עם צורות צבעוניות!",                          icon: Building,       emoji: "🏗️", color: "bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600",              href: "/games/building",        available: true, order: 25 },
  { id: "tetris",          title: "טטריס לילדים",                   description: "המשחק הכי כיפי בעולם!",                                   icon: Layers,         emoji: "🟦", color: "bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700",         href: "/games/tetris",          available: true, order: 26 },
  { id: "sports",          title: "משחק ספורט",                     description: "למד על ספורט ופעילות גופנית!",                            icon: Trophy,         emoji: "⚽", color: "bg-green-500 hover:bg-green-600",                                                                          href: "/games/sports",          available: true, order: 27 },
  { id: "kitchen",         title: "משחק כלי מטבח",                  description: "למד על כלי מטבח ובישול!",                                 icon: ChefHat,        emoji: "🍳", color: "bg-orange-500 hover:bg-orange-600",                                                                        href: "/games/kitchen",         available: true, order: 28 },
  { id: "body-parts",      title: "משחק חלקי הגוף",                 description: "למד על חלקי הגוף השונים!",                                icon: Hand,           emoji: "🖐️", color: "bg-pink-500 hover:bg-pink-600",                                                                          href: "/games/body-parts",      available: true, order: 29 },
  { id: "dinosaurs",       title: "משחק דינוזאורים",                description: "למד על דינוזאורים מדהימים מהעבר!",                       icon: Bone,           emoji: "🦖", color: "bg-green-600 hover:bg-green-700",                                                                          href: "/games/dinosaurs",       available: true, order: 31 },
  { id: "world-food",      title: "משחק מזון מסביב לעולם",          description: "הכר מאכלים מתרבויות שונות!",                             icon: Utensils,       emoji: "🍜", color: "bg-purple-500 hover:bg-purple-600",                                                                       href: "/games/world-food",      available: true, order: 32 },
  { id: "recycling",       title: "משחק מחזור וקיימות",             description: "למד על מחזור וחשיבות שמירה על הסביבה!",                  icon: Recycle,        emoji: "♻️", color: "bg-green-500 hover:bg-green-600",                                                                          href: "/games/recycling",       available: true, order: 33 },
  { id: "medicine",        title: "משחק מרקחת ותרופות",             description: "הכר כלי רפואה ומתן עזרה ראשונה!",                       icon: Pill,           emoji: "💊", color: "bg-red-500 hover:bg-red-600",                                                                             href: "/games/medicine",        available: true, order: 34 },
  { id: "nature-sounds",   title: "משחק צלילי הטבע",                description: "הקשב לקולות הטבע ובעלי החיים!",                          icon: Volume2,        emoji: "🌿", color: "bg-teal-500 hover:bg-teal-600",                                                                           href: "/games/nature-sounds",   available: true, order: 35 },
  { id: "seasons-holidays",title: "משחק עונות השנה ומועדים",        description: "למד על עונות השנה והחגים היהודיים!",                     icon: Calendar,       emoji: "🍂", color: "bg-amber-500 hover:bg-amber-600",                                                                         href: "/games/seasons-holidays",available: true, order: 36 },
  { id: "shopping-money",  title: "משחק קניות וכסף",                description: "למד על כסף, מחירים וקניות!",                             icon: ShoppingCart,   emoji: "🛒", color: "bg-indigo-500 hover:bg-indigo-600",                                                                       href: "/games/shopping-money",  available: true, order: 38 },
  { id: "road-safety",     title: "משחק בטיחות בדרכים",             description: "למד כללי בטיחות חשובים בדרכים!",                        icon: Shield,         emoji: "🚦", color: "bg-orange-500 hover:bg-orange-600",                                                                       href: "/games/road-safety",     available: true, order: 39 },
  { id: "ocean-life",      title: "משחק חיי הים",                   description: "גלה את עולם הים הקסום וחיותיו המרהיבות!",               icon: Waves,          emoji: "🐠", color: "bg-blue-600 hover:bg-blue-700",                                                                           href: "/games/ocean-life",      available: true, order: 40 },
  { id: "garden-plants",   title: "משחק הגינה והצמחים",             description: "למד על צמחים, פרחים וגידול בגינה!",                     icon: Flower,         emoji: "🌸", color: "bg-green-500 hover:bg-green-600",                                                                         href: "/games/garden-plants",   available: true, order: 41 },
  { id: "magic-fairy-tales",title: "משחק אגדות וקסמים",             description: "היכנס לעולם הקסמים והאגדות הקלאסיות!",                  icon: Sparkles,       emoji: "🧚", color: "bg-purple-500 hover:bg-purple-600",                                                                       href: "/games/magic-fairy-tales",available: true, order: 42 },
  { id: "circus-show",      title: "משחק הקרקס והמופע",             description: "הצטרף למופע הקרקס המרהיב ולמשחקי כושר!",               icon: PartyPopper,    emoji: "🎪", color: "bg-pink-500 hover:bg-pink-600",                                                                          href: "/games/circus-show",     available: true, order: 45 },
  { id: "virtual-reality",  title: "משחק מציאות מדומה",             description: "גלה עולמות חדשים במציאות מדומה!",                       icon: Cpu,            emoji: "🥽", color: "bg-purple-600 hover:bg-purple-700",                                                                      href: "/games/virtual-reality", available: true, order: 46 },
  { id: "new-professions",  title: "מקצועות מודרניים",              description: "למד על מקצועות חדשים וטכנולוגיים!",                     icon: Briefcase,      emoji: "💼", color: "bg-gray-600 hover:bg-gray-700",                                                                          href: "/games/new-professions", available: true, order: 47 },
  { id: "advanced-weather", title: "מזג אוויר מתקדם",               description: "למד על תופעות מזג אוויר מיוחדות!",                      icon: CloudRain,      emoji: "⛈️", color: "bg-blue-700 hover:bg-blue-800",                                                                          href: "/games/advanced-weather",available: true, order: 48 },
  { id: "advanced-colors",  title: "צבעים מתקדמים",                 description: "גלה צבעים מיוחדים וערבובי צבעים!",                     icon: Rainbow,        emoji: "🌈", color: "bg-gradient-to-r from-red-400 via-yellow-400 to-blue-400",                                          href: "/games/advanced-colors", available: true, order: 49 },
  { id: "jewish-holidays",  title: "חגים יהודיים",                  description: "למד על חגי ישראל ומסורותיהם!",                          icon: Star,           emoji: "🕎", color: "bg-yellow-600 hover:bg-yellow-700",                                                                      href: "/games/jewish-holidays", available: true, order: 50 },
];
