import {
  Brain,
  Mic,
  Activity,
  TouchpadIcon as Touch,
  Clock,
  Earth,
  Bird,
  Bug,
  Zap,
  Paintbrush,
  Mountain,
  Crown,
  BookOpen,
  Calendar,
  Calculator,
  Dog,
  Hash,
  PenLine,
  ArrowLeftRight,
  Languages,
  Lightbulb,
  Trophy,
  Music,
  Flag,
  Divide,
  MapPin,
  SmilePlus,
  Leaf,
  Box,
  Bone,
  Car,
  Truck,
  Utensils,
  Map,
  Baby,
  CircleDot,
} from "lucide-react";
import type { GameRegistration } from "@/lib/types/games/base";

export const gamesRegistryBatch2: GameRegistration[] = [
  { id: "logic-games",      title: "משחקי חשיבה ולוגיקה",           description: "פתח את יכולות החשיבה והלוגיקה!",                        icon: Brain,          emoji: "🧩", color: "bg-indigo-700 hover:bg-indigo-800",                                                                      href: "/games/logic-games",     available: true, order: 51 },
  { id: "sound-imitation",  title: "חיקוי קולות ורעשים",            description: "חקה קולות של חיות, מכונות וטבע!",                      icon: Mic,            emoji: "🎤", color: "bg-green-600 hover:bg-green-700",                                                                        href: "/games/sound-imitation", available: true, order: 52 },
  { id: "body-movements",   title: "תנועות גוף וריקוד",             description: "תרגל תנועות, יוגה וריקוד אינטראקטיבי!",                icon: Activity,       emoji: "🤸", color: "bg-pink-600 hover:bg-pink-700",                                                                         href: "/games/body-movements",  available: true, order: 53 },
  { id: "touch-senses",     title: "מגע וחושים",                    description: "חקור מרקמים, טמפרטורות וחושי גוף!",                    icon: Touch,          emoji: "🤚", color: "bg-orange-600 hover:bg-orange-700",                                                                      href: "/games/touch-senses",    available: true, order: 54 },
  { id: "emotional-social", title: "מציאות רגשית וחברתית",          description: "פתח אינטליגנציה רגשית וחברתית!",                        icon: Brain,          emoji: "💖", color: "bg-purple-700 hover:bg-purple-800",                                                                     href: "/games/emotional-social",available: true, order: 55 },
  { id: "time-clock",       title: "זמן ושעות היום",                 description: "למד על זמן, שעות, ימים ועונות!",                       icon: Clock,          emoji: "⏰", color: "bg-blue-800 hover:bg-blue-900",                                                                         href: "/games/time-clock",      available: true, order: 56 },
  { id: "climate-planet",   title: "אקלים וכדור הארץ",              description: "גלה יבשות, אוקיינוסים ואזורי אקלים!",                  icon: Earth,          emoji: "🌍", color: "bg-teal-700 hover:bg-teal-800",                                                                         href: "/games/climate-planet",  available: true, order: 57 },
  { id: "birds",            title: "משחק ציפורים",                   description: "הכר ציפורים מדהימות מרחבי העולם!",                     icon: Bird,           emoji: "🦅", color: "bg-sky-500 hover:bg-sky-600",                                                                           href: "/games/birds",           available: true, order: 58 },
  { id: "bugs-insects",     title: "חרקים ופרפרים",                  description: "עולם זעיר ומרתק של חרקים!",                             icon: Bug,            emoji: "🦋", color: "bg-lime-600 hover:bg-lime-700",                                                                         href: "/games/bugs-insects",    available: true, order: 59 },
  { id: "superheroes",      title: "גיבורי על",                     description: "למד על כוחות סופר וגיבורים מדהימים!",                  icon: Zap,            emoji: "🦸", color: "bg-yellow-500 hover:bg-yellow-600",                                                                     href: "/games/superheroes",     available: true, order: 60 },
  { id: "art-craft",        title: "אמנות ויצירה",                   description: "הכר כלי אמנות וצור יצירות מדהימות!",                   icon: Paintbrush,     emoji: "🖌️", color: "bg-rose-500 hover:bg-rose-600",                                                                         href: "/games/art-craft",       available: true, order: 61 },
  { id: "camping",          title: "טיול ושטח",                     description: "הכן את הציוד להרפתקאה בטבע!",                          icon: Mountain,       emoji: "⛺", color: "bg-green-700 hover:bg-green-800",                                                                       href: "/games/camping",         available: true, order: 62 },
  { id: "fairy-tale-chars", title: "דמויות מאגדות",                  description: "גלה דמויות קסומות מאגדות מרתקות!",                    icon: Crown,          emoji: "🧚", color: "bg-violet-600 hover:bg-violet-700",                                                                     href: "/games/fairy-tale-chars",available: true, order: 63 },
  { id: "tzadikim",         title: "סיפורי צדיקים",                  description: "למד על גדולי ישראל ומה שלמדנו מהם!",                   icon: BookOpen,       emoji: "📜", color: "bg-amber-600 hover:bg-amber-700",                                                                       href: "/games/tzadikim",        available: true, order: 64 },
  { id: "holidays",         title: "חגי ישראל",                     description: "למד על חגי ישראל ומשמעותם!",                           icon: Calendar,       emoji: "🕍", color: "bg-yellow-500 hover:bg-yellow-600",                                                                     href: "/games/holidays",        available: true, order: 65 },
  { id: "multiplication",   title: "לוח הכפל",                      description: "תרגל כפל במהירות עם טיימר!",                           icon: Calculator,     emoji: "✖️", color: "bg-blue-600 hover:bg-blue-700",                                                                         href: "/games/multiplication",  available: true, order: 66 },
  { id: "animals",          title: "בעלי חיים",                     description: "זהה בעלי חיים ולמד עליהם!",                            icon: Dog,            emoji: "🐘", color: "bg-green-600 hover:bg-green-700",                                                                       href: "/games/animals",         available: true, order: 67 },
  { id: "word-builder",     title: "בניית מילים",                    description: "הרכב מילים בעברית מאותיות מפוזרות!",                   icon: BookOpen,       emoji: "🔤", color: "bg-purple-600 hover:bg-purple-700",                                                                     href: "/games/word-builder",    available: true, order: 68 },
  { id: "reflex",           title: "מהירות תגובה",                   description: "לחץ על הסמלים לפני שהם נעלמים!",                      icon: Zap,            emoji: "⚡", color: "bg-red-500 hover:bg-red-600",                                                                           href: "/games/reflex",          available: true, order: 69 },
  { id: "arithmetic",       title: "חשבון מהיר",                    description: "חבר, חסר וכפל במהירות!",                               icon: Calculator,     emoji: "➕", color: "bg-blue-500 hover:bg-blue-600",                                                                         href: "/games/arithmetic",      available: true, order: 70 },
  { id: "geography-flags",      title: "דגלי העולם",    description: "לאיזו מדינה שייך הדגל?",        icon: Earth, emoji: "🚩", color: "bg-teal-600 hover:bg-teal-700", href: "/games/geography-flags",      available: true, order: 71 },
  { id: "geography-capitals",   title: "בירות העולם",   description: "מה הבירה של כל מדינה?",         icon: Earth, emoji: "🏛️", color: "bg-teal-700 hover:bg-teal-800", href: "/games/geography-capitals",   available: true, order: 132 },
  { id: "geography-continents", title: "יבשות העולם",   description: "באיזו יבשת נמצאת המדינה?",     icon: Earth, emoji: "🌍", color: "bg-cyan-600 hover:bg-cyan-700",  href: "/games/geography-continents", available: true, order: 133 },
  { id: "trivia",           title: "ידע כללי",                      description: "שאלות על טבע, מדע, חלל ועוד!",                        icon: Brain,          emoji: "🎯", color: "bg-amber-500 hover:bg-amber-600",                                                                       href: "/games/trivia",          available: true, order: 72 },
  { id: "color-mix",        title: "ערבוב צבעים",                   description: "מה מקבלים כשמערבבים צבעים?",                          icon: Paintbrush,     emoji: "🎨", color: "bg-pink-500 hover:bg-pink-600",                                                                         href: "/games/color-mix",       available: true, order: 73 },
  { id: "science",          title: "מדע לילדים",                    description: "גוף, חלל, טבע ופיזיקה לילדים!",                       icon: Brain,          emoji: "🔬", color: "bg-emerald-600 hover:bg-emerald-700",                                                                   href: "/games/science",         available: true, order: 74 },
  { id: "clock",            title: "הכרת השעון",                    description: "למד לקרוא שעון עם שעון אנלוגי!",                      icon: Clock,          emoji: "🕐", color: "bg-violet-600 hover:bg-violet-700",                                                                     href: "/games/clock",           available: true, order: 75 },
  { id: "spelling",         title: "כתיב עברי",                     description: "בחר את האיות הנכון בעברית!",                          icon: PenLine,        emoji: "📝", color: "bg-rose-500 hover:bg-rose-600",                                                                         href: "/games/spelling",        available: true, order: 76 },
  { id: "sequences",        title: "סדרות מספרים",                  description: "מה המספר הבא בסדרה?",                                 icon: Hash,           emoji: "🔢", color: "bg-cyan-600 hover:bg-cyan-700",                                                                         href: "/games/sequences",       available: true, order: 77 },
  { id: "opposites",        title: "ניגודים",                       description: "גדול-קטן, חם-קר ועוד הפכים!",                         icon: ArrowLeftRight, emoji: "↔️", color: "bg-orange-500 hover:bg-orange-600",                                                                     href: "/games/opposites",       available: true, order: 78 },
  { id: "world-languages",  title: "שפות העולם",                    description: "באיזו שפה מדברים בכל מדינה?",                         icon: Earth,          emoji: "🌐", color: "bg-emerald-500 hover:bg-emerald-600",                                                                   href: "/games/world-languages", available: true, order: 79 },
  { id: "riddles",          title: "חידות לילדים",                  description: "פתור חידות מסקרנות ומהנות!",                          icon: Lightbulb,      emoji: "💡", color: "bg-purple-600 hover:bg-purple-700",                                                                     href: "/games/riddles",         available: true, order: 80 },
  { id: "sports-quiz",      title: "חידון ספורט",                   description: "שאלות על עולם הספורט!",                               icon: Trophy,         emoji: "🏆", color: "bg-green-600 hover:bg-green-700",                                                                       href: "/games/sports-quiz",     available: true, order: 81 },
  { id: "instruments",      title: "כלי נגינה",                     description: "זהה כלי נגינה לפי תיאורם!",                          icon: Music,          emoji: "🎸", color: "bg-amber-500 hover:bg-amber-600",                                                                       href: "/games/instruments",     available: true, order: 82 },
  { id: "israel",           title: "ישראל שלי",                     description: "ידע על מדינת ישראל!",                                 icon: Flag,           emoji: "🇮🇱", color: "bg-blue-600 hover:bg-blue-700",                                                                        href: "/games/israel",          available: true, order: 83 },
  { id: "english-words",    title: "אנגלית לילדים",                 description: "למד מילים בסיסיות באנגלית!",                         icon: Languages,      emoji: "🔤", color: "bg-indigo-600 hover:bg-indigo-700",                                                                     href: "/games/english-words",   available: true, order: 84 },
  { id: "fractions",        title: "שברים פשוטים",                  description: "זהה שברים לפי ייצוג ויזואלי!",                       icon: Divide,         emoji: "½", color: "bg-purple-600 hover:bg-purple-700",                                                                      href: "/games/fractions",       available: true, order: 85 },
  { id: "capitals",         title: "בירות העולם",                   description: "מה הבירה של כל מדינה?",                              icon: MapPin,         emoji: "🏛️", color: "bg-red-600 hover:bg-red-700",                                                                           href: "/games/capitals",        available: true, order: 86 },
  { id: "emotions",         title: "עולם הרגשות",                   description: "זהה רגשות לפי תיאור!",                               icon: SmilePlus,      emoji: "😊", color: "bg-orange-500 hover:bg-orange-600",                                                                     href: "/games/emotions",        available: true, order: 87 },
  { id: "nature",           title: "עולם הטבע",                     description: "למד על הטבע סביבנו!",                                 icon: Leaf,           emoji: "🌿", color: "bg-green-600 hover:bg-green-700",                                                                       href: "/games/nature",          available: true, order: 88 },
  { id: "shapes-3d",        title: "גופים גיאומטריים",              description: "למד גופים תלת-ממדיים!",                               icon: Box,            emoji: "📐", color: "bg-indigo-500 hover:bg-indigo-600",                                                                     href: "/games/shapes-3d",       available: true, order: 89 },
  { id: "human-body",       title: "גוף האדם",                      description: "גלה את פלאות גוף האדם!",                             icon: Bone,           emoji: "🫀", color: "bg-red-500 hover:bg-red-600",                                                                           href: "/games/human-body",      available: true, order: 90 },
  { id: "transport",        title: "כלי תחבורה",                    description: "גלה כלי רכב מהיבשה, הים והאוויר!",                  icon: Car,            emoji: "🚗", color: "bg-sky-500 hover:bg-sky-600",                                                                           href: "/games/transport",       available: true, order: 91 },
  { id: "vehicles",          title: "כלי רכב",                       description: "למד כלי רכב דרך שמיעה — מכוניות, אופנועים ועוד!",  icon: Truck,          emoji: "🚛", color: "bg-blue-500 hover:bg-blue-600",                                                                          href: "/games/vehicles",        available: true, order: 134 },
  { id: "healthy-food",     title: "אוכל בריא",                     description: "למד על תזונה נכונה ומזינה!",                         icon: Utensils,       emoji: "🥗", color: "bg-lime-500 hover:bg-lime-600",                                                                         href: "/games/healthy-food",    available: true, order: 92 },
  { id: "continents",       title: "יבשות העולם",                   description: "גלה את 7 יבשות כדור הארץ!",                          icon: Map,            emoji: "🌍", color: "bg-teal-500 hover:bg-teal-600",                                                                         href: "/games/continents",      available: true, order: 93 },
  { id: "family",           title: "המשפחה",                        description: "למד על קשרים משפחתיים!",                             icon: Baby,           emoji: "👨‍👩‍👧‍👦", color: "bg-rose-500 hover:bg-rose-600",                                                                  href: "/games/family",          available: true, order: 94 },
  { id: "soccer",           title: "כדורגל",                        description: "שאלות על ספורט המלכים!",                             icon: CircleDot,      emoji: "⚽", color: "bg-green-600 hover:bg-green-700",                                                                       href: "/games/soccer",          available: true, order: 95 },
  { id: "singular-plural", title: "יחיד ורבים",                    description: "למד צורות רבים בעברית!",                             icon: Brain,          emoji: "📝", color: "bg-teal-500 hover:bg-teal-600",                                                                         href: "/games/singular-plural", available: true, order: 135 },
  { id: "morning-routine", title: "שגרת הבוקר",                    description: "מה בא אחרי מה בשגרת היום?",                          icon: Clock,          emoji: "🌅", color: "bg-amber-500 hover:bg-amber-600",                                                                       href: "/games/morning-routine", available: true, order: 136 },
  { id: "phonics",          title: "פוניקה עברית",                  description: "שמע צליל ובחר את האות הנכונה!",                      icon: Mic,            emoji: "🔊", color: "bg-violet-500 hover:bg-violet-600",                                                                     href: "/games/phonics",         available: true, order: 140 },
];
