import {
  Flag,
  CircleDot,
  Car,
  Landmark,
  Star,
  Palette,
  Cpu,
  Dog,
  Cat,
  Trophy,
  Bird,
  Bug,
  Gamepad2,
  Crown,
  Music,
  PenLine,
  MapPin,
  Hash,
  Layers,
  Repeat,
  Zap,
  ArrowLeftRight,
  BookOpen,
  Leaf,
  ShieldCheck,
  Type,
  AlignLeft,
  Calculator,
} from "lucide-react";
import type { GameRegistration } from "@/lib/types/games/base";

export const gamesRegistryBatch4: GameRegistration[] = [
  // משחקי גיאוגרפיה
  {
    id: "flags",
    title: "דגלי מדינות",
    description: "זהה דגלים של מדינות מסביב לעולם!",
    icon: Flag,
    emoji: "🚩",
    color: "bg-blue-600 hover:bg-blue-700",
    href: "/games/flags",
    available: true,
    order: 116,
  },
  // משחקי ספורט
  {
    id: "soccer-logos",
    title: "סמלי כדורגל",
    description: "זהה סמלים של קבוצות כדורגל מסביב לעולם!",
    icon: CircleDot,
    emoji: "⚽",
    color: "bg-green-600 hover:bg-green-700",
    href: "/games/soccer-logos",
    available: true,
    order: 117,
  },
  // משחקי תחבורה וסמלים
  {
    id: "car-brands",
    title: "לוגואים של מכוניות",
    description: "זהה לוגואים של מותגי מכוניות מפורסמים!",
    icon: Car,
    emoji: "🚗",
    color: "bg-blue-700 hover:bg-blue-800",
    href: "/games/car-brands",
    available: true,
    order: 118,
  },
  {
    id: "world-landmarks",
    title: "אתרים מפורסמים",
    description: "זהה אתרים מפורסמים מסביב לעולם!",
    icon: Landmark,
    emoji: "🗼",
    color: "bg-teal-600 hover:bg-teal-700",
    href: "/games/world-landmarks",
    available: true,
    order: 119,
  },
  {
    id: "solar-system",
    title: "מערכת השמש",
    description: "זהה כוכבי לכת וגרמי שמים!",
    icon: Star,
    emoji: "🪐",
    color: "bg-indigo-900 hover:bg-indigo-950",
    href: "/games/solar-system",
    available: true,
    order: 120,
  },
  {
    id: "famous-paintings",
    title: "ציורים מפורסמים",
    description: "זהה ציורים מפורסמים מהיסטוריית האמנות!",
    icon: Palette,
    emoji: "🖼️",
    color: "bg-amber-800 hover:bg-amber-900",
    href: "/games/famous-paintings",
    available: true,
    order: 121,
  },
  {
    id: "tech-logos",
    title: "לוגואים טכנולוגיה",
    description: "זהה לוגואים של חברות הטכנולוגיה הגדולות!",
    icon: Cpu,
    emoji: "📱",
    color: "bg-sky-700 hover:bg-sky-800",
    href: "/games/tech-logos",
    available: true,
    order: 122,
  },
  {
    id: "dog-breeds",
    title: "גזעי כלבים",
    description: "זהה גזעי כלבים מסביב העולם!",
    icon: Dog,
    emoji: "🐕",
    color: "bg-amber-600 hover:bg-amber-700",
    href: "/games/dog-breeds",
    available: true,
    order: 123,
  },
  {
    id: "cat-breeds",
    title: "גזעי חתולים",
    description: "זהה גזעי חתולים מסביב העולם!",
    icon: Cat,
    emoji: "🐱",
    color: "bg-purple-600 hover:bg-purple-700",
    href: "/games/cat-breeds",
    available: true,
    order: 124,
  },
  {
    id: "nba-teams",
    title: "קבוצות NBA",
    description: "זהה לוגואים של קבוצות הבסקטבול הגדולות!",
    icon: Trophy,
    emoji: "🏀",
    color: "bg-orange-600 hover:bg-orange-700",
    href: "/games/nba-teams",
    available: true,
    order: 125,
  },
  {
    id: "exotic-birds",
    title: "ציפורים אקזוטיות",
    description: "זהה ציפורים מסביב העולם!",
    icon: Bird,
    emoji: "🦩",
    color: "bg-sky-600 hover:bg-sky-700",
    href: "/games/exotic-birds",
    available: true,
    order: 126,
  },
  {
    id: "butterflies",
    title: "פרפרים",
    description: "זהה פרפרים ועשים מסביב העולם!",
    icon: Bug,
    emoji: "🦋",
    color: "bg-pink-500 hover:bg-pink-600",
    href: "/games/butterflies",
    available: true,
    order: 127,
  },
  {
    id: "taki",
    title: "טאקי",
    description: "משחק הקלפים הישראלי הקלאסי — שחק נגד המחשב!",
    icon: Gamepad2,
    emoji: "🃏",
    color: "bg-emerald-600 hover:bg-emerald-700",
    href: "/games/taki",
    available: true,
    order: 128,
  },
  {
    id: "checkers",
    title: "דמקה",
    description: "משחק הדמקה הקלאסי — קפוץ מעל האסימונים ונצח!",
    icon: Gamepad2,
    emoji: "♟️",
    color: "bg-amber-700 hover:bg-amber-800",
    href: "/games/checkers",
    available: true,
    order: 129,
  },
  {
    id: "chess",
    title: "שחמט",
    description: "שחמט קלאסי נגד המחשב — הביס את המלך!",
    icon: Crown,
    emoji: "♚",
    color: "bg-slate-700 hover:bg-slate-800",
    href: "/games/chess",
    available: true,
    order: 130,
  },
  {
    id: "shesh-besh",
    title: "שש-בש",
    description: "משחק השש-בש הקלאסי — הטל קוביות ורוקן את הלוח!",
    icon: Gamepad2,
    emoji: "🎲",
    color: "bg-stone-600 hover:bg-stone-700",
    href: "/games/shesh-besh",
    available: true,
    order: 131,
  },
  {
    id: "days-of-week",
    title: "ימות השבוע",
    description: "למד את ימות השבוע בעברית!",
    icon: Star,
    emoji: "📅",
    color: "bg-blue-400 hover:bg-blue-500",
    href: "/games/days-of-week",
    available: true,
    order: 141,
  },
  {
    id: "months-of-year",
    title: "חודשי השנה",
    description: "למד את חודשי השנה בעברית!",
    icon: Star,
    emoji: "🗓️",
    color: "bg-purple-400 hover:bg-purple-500",
    href: "/games/months-of-year",
    available: true,
    order: 142,
  },
  {
    id: "ordinals",
    title: "מספרים סודריים",
    description: "ראשון, שני, שלישי — למד מספרים סודריים!",
    icon: Star,
    emoji: "🥇",
    color: "bg-amber-500 hover:bg-amber-600",
    href: "/games/ordinals",
    available: true,
    order: 143,
  },
  {
    id: "rhyming",
    title: "חרוזים",
    description: "מה מתחרז עם X? — מצא את המילה החרוזית!",
    icon: Music,
    emoji: "🎵",
    color: "bg-violet-500 hover:bg-violet-600",
    href: "/games/rhyming",
    available: true,
    order: 144,
  },
  {
    id: "adjectives",
    title: "שמות תואר",
    description: "גדול, קטן, שמח, עצוב — למד לתאר עצמים!",
    icon: PenLine,
    emoji: "🎨",
    color: "bg-pink-500 hover:bg-pink-600",
    href: "/games/adjectives",
    available: true,
    order: 145,
  },
  {
    id: "spatial-concepts",
    title: "מושגי מרחב",
    description: "מעל, מתחת, בתוך — למד מושגי מיקום!",
    icon: MapPin,
    emoji: "🗺️",
    color: "bg-green-500 hover:bg-green-600",
    href: "/games/spatial-concepts",
    available: true,
    order: 146,
  },
  {
    id: "number-words",
    title: "מספרים כמילים",
    description: "אחד, שתיים, שלוש — קרא מספרים בעברית!",
    icon: Hash,
    emoji: "🔢",
    color: "bg-orange-500 hover:bg-orange-600",
    href: "/games/number-words",
    available: true,
    order: 147,
  },
  {
    id: "verbs",
    title: "פעלים",
    description: "מה הוא עושה? — רץ, ישן, שר — למד פעלים בעברית!",
    icon: Zap,
    emoji: "🏃",
    color: "bg-teal-500 hover:bg-teal-600",
    href: "/games/verbs",
    available: true,
    order: 148,
  },
  {
    id: "visual-opposites",
    title: "ניגודים",
    description: "גדול ↔ קטן, חם ↔ קר — למד מושגי ניגוד!",
    icon: ArrowLeftRight,
    emoji: "🔄",
    color: "bg-purple-500 hover:bg-purple-600",
    href: "/games/visual-opposites",
    available: true,
    order: 149,
  },
  {
    id: "english-cards",
    title: "אנגלית ראשונה",
    description: "שמע מילה אנגלית ובחר את התמונה הנכונה!",
    icon: BookOpen,
    emoji: "🔤",
    color: "bg-indigo-600 hover:bg-indigo-700",
    href: "/games/english-cards",
    available: true,
    order: 150,
  },
  {
    id: "sorting",
    title: "מיון לקטגוריות",
    description: "כלב או כסא? — מיין פריטים לקטגוריות!",
    icon: Layers,
    emoji: "🗂️",
    color: "bg-emerald-500 hover:bg-emerald-600",
    href: "/games/sorting",
    available: true,
    order: 151,
  },
  {
    id: "patterns",
    title: "זיהוי דפוסים",
    description: "🔴🔵🔴❓ — מה בא הלאה בדפוס?",
    icon: Repeat,
    emoji: "🔵",
    color: "bg-sky-500 hover:bg-sky-600",
    href: "/games/patterns",
    available: true,
    order: 152,
  },
  {
    id: "skip-counting",
    title: "ספירה לפי קפיצות",
    description: "ספור לפי 2, 5 ו-10 — מלא את המספר החסר!",
    icon: Hash,
    emoji: "🔢",
    color: "bg-teal-500 hover:bg-teal-600",
    href: "/games/skip-counting",
    available: true,
    order: 153,
  },
  {
    id: "division",
    title: "חילוק",
    description: "12 ÷ 3 = ? — חלק פריטים לקבוצות שוות!",
    icon: Hash,
    emoji: "➗",
    color: "bg-blue-500 hover:bg-blue-600",
    href: "/games/division",
    available: true,
    order: 154,
  },
  {
    id: "maze",
    title: "מבוך",
    description: "נווט דרך המבוך, אסוף כוכבים והגע לדלת — 5 רמות מאתגרות!",
    icon: Gamepad2,
    emoji: "🧩",
    color: "bg-indigo-600 hover:bg-indigo-700",
    href: "/games/maze",
    available: true,
    order: 155,
  },
  {
    id: "life-cycles",
    title: "מחזור חיים",
    description: "סדר את שלבי מחזור החיים — פרפר, צפרדע ועוד!",
    icon: Leaf,
    emoji: "🦋",
    color: "bg-green-500 hover:bg-green-600",
    href: "/games/life-cycles",
    available: true,
    order: 156,
  },
  {
    id: "nikud",
    title: "ניקוד עברי",
    description: "זהה את הניקוד — פַּתַח, חִירִיק, חוֹלֵם ועוד!",
    icon: BookOpen,
    emoji: "🔤",
    color: "bg-violet-500 hover:bg-violet-600",
    href: "/games/nikud",
    available: true,
    order: 157,
  },
  {
    id: "gender",
    title: "זכר ונקבה",
    description: "למד לזהות האם מילה היא זכר או נקבה בעברית!",
    icon: Type,
    emoji: "🧒",
    color: "bg-violet-400 hover:bg-violet-500",
    href: "/games/gender",
    available: true,
    order: 158,
  },
  {
    id: "final-letters",
    title: "אותיות סופיות",
    description: "למד את חמש האותיות הסופיות: ם ן ף ץ ך",
    icon: AlignLeft,
    emoji: "🔤",
    color: "bg-indigo-500 hover:bg-indigo-600",
    href: "/games/final-letters",
    available: true,
    order: 159,
  },
  {
    id: "alphabet-order",
    title: "סדר האלפבית",
    description: "תרגל את סדר האותיות באלפבית העברי!",
    icon: BookOpen,
    emoji: "🔠",
    color: "bg-emerald-500 hover:bg-emerald-600",
    href: "/games/alphabet-order",
    available: true,
    order: 160,
  },
  {
    id: "personal-safety",
    title: "בטיחות אישית",
    description: "הכר את אנשי הבטיחות ולמד כיצד לשמור על עצמך!",
    icon: ShieldCheck,
    emoji: "🛡️",
    color: "bg-purple-500 hover:bg-purple-600",
    href: "/games/personal-safety",
    available: true,
    order: 161,
  },
  {
    id: "visual-addition",
    title: "חיבור חזותי",
    description: "ספור את האובייקטים וחבר אותם — מתאים לגילאי 3-5!",
    icon: Hash,
    emoji: "➕",
    color: "bg-green-500 hover:bg-green-600",
    href: "/games/visual-addition",
    available: true,
    order: 162,
  },
  {
    id: "gematria",
    title: "גמטריה",
    description: "למד את ערכי האותיות העבריות וחשב גמטריה!",
    icon: Calculator,
    emoji: "א",
    color: "bg-violet-500 hover:bg-violet-600",
    href: "/games/gematria",
    available: true,
    order: 163,
  },
  {
    id: "word-chain",
    title: "שרשרת מילים",
    description: "כל מילה מתחילה באות האחרונה של הקודמת — בנה שרשרת ארוכה!",
    icon: AlignLeft,
    emoji: "🔗",
    color: "bg-indigo-500 hover:bg-indigo-600",
    href: "/games/word-chain",
    available: true,
    order: 164,
  },
  {
    id: "letter-defender",
    title: "מגן האותיות",
    description: "הצב מגדלים כדי לעצור מילים שגויות — הגן על האיות הנכון!",
    icon: Layers,
    emoji: "🏰",
    color: "bg-emerald-600 hover:bg-emerald-700",
    href: "/games/letter-defender",
    available: true,
    order: 165,
  },
  {
    id: "visual-logic",
    title: "לוגיקה חזותית",
    description: "מצא את הפריט החסר בתבנית — חשיבה לוגית וזיהוי דפוסים!",
    icon: Layers,
    emoji: "🧩",
    color: "bg-indigo-500 hover:bg-indigo-600",
    href: "/games/visual-logic",
    available: true,
    order: 166,
  },
];
