import type { GameUIConfig } from './gameUIConfig.types';

export const activitiesConfigs: Partial<Record<string, GameUIConfig>> = {
  instruments: {
    title: "🎵 משחק כלי נגינה 🎸",
    subTitle: "למד כלי נגינה דרך שמיעה!",
    itemsTitle: "כלי הנגינה שנלמד:",
    itemsDescription: "לחץ על כלי נגינה כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה כלי נגינה אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הוא נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על כלי הנגינה הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fef3c7 0%, #f59e0b 25%, #d97706 50%, #b45309 75%, #92400e 100%)",
      header: "text-white",
      subHeader: "text-yellow-100",
      itemsDescription: "text-yellow-100",
      button: { from: "yellow", to: "amber" },
      stepsBg: "bg-yellow-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  building: {
    title: "🏗️ סטודיו הבנייה הקסום 🏗️",
    subTitle: "בנה יצירות עם צורות צבעוניות!",
    itemsTitle: "הכלים הקסומים:",
    itemsDescription: "בחר צורות וצבעים לבניית היצירה שלך!",
    steps: [
      { icon: "🎨", title: "1. תבחר", description: "צבע וכלי בנייה" },
      { icon: "🔨", title: "2. תבנה", description: "גרור ושים צורות" },
      { icon: "✨", title: "3. תיצור", description: "יצירה קסומה!" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-white",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-4 gap-6 max-w-4xl mx-auto",
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "בנה את היצירה שלך!",
    challengeIcon: "🏗️🎨✨🌈",
    challengeDescription: "השתמש בצורות וצבעים ליצירה!",
    itemLabel: "כלי בנייה",
    tip: "💡 טיפ: גרור כדי להזיז, לחץ פעמיים לסיבוב!",
    tipDescription: "השתמש בכלים השונים ליצירת יצירות קסומות",
  },

  tetris: {
    title: "🧩 טטריס לילדים 🧩",
    subTitle: "המשחק הכי כיפי בעולם!",
    itemsTitle: "איך משחקים:",
    itemsDescription: "למד את החוקים והתחל לשחק!",
    steps: [
      { icon: "⬇️", title: "1. נפילה", description: "חלקים נופלים מלמעלה" },
      { icon: "🔄", title: "2. סיבוב", description: "סובב חלקים בחץ למעלה" },
      { icon: "➡️", title: "3. הזזה", description: "הזז ימינה ושמאלה" },
      { icon: "⚡", title: "4. ניקוי", description: "מלא שורות כדי לנקות" },
      { icon: "🏆", title: "5. ניקוד", description: "השג ניקוד גבוה!" },
    ],
    colors: {
      background: "bg-gradient-to-br from-purple-600 via-blue-600 to-indigo-700",
      header: "text-yellow-300",
      subHeader: "text-white/90",
      itemsDescription: "text-blue-100",
      button: { from: "from-yellow-400", to: "to-orange-500" },
      stepsBg: "bg-white/20",
    },
    grid: {
      className: "grid-cols-1",
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "שחק טטריס!",
    challengeIcon: "🧩🎮⬇️🔄",
    challengeDescription: "סדר את החלקים ונקה שורות!",
    itemLabel: "חלק טטריס",
    tip: "💡 טיפ: נסה לחשוב איך לסדר החלקים מראש!",
    tipDescription: "השתמש בחיצי המקלדת או בכפתורי המגע לשלטון",
  },

  // =============== משחקים חדשים ===============
  
  sports: {
    title: "⚽ משחק ספורט ⚽",
    subTitle: "למד על ספורט ופעילות גופנית!",
    itemsTitle: "הספורט שנלמד:",
    itemsDescription: "לחץ על ספורט כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה ספורט אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם הספורט" },
      { icon: "👆", title: "3. תלחץ", description: "על הספורט הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #a8e6cf 0%, #dcedc1 25%, #ffd3e1 50%, #ffecd2 75%, #fcb69f 100%)",
      header: "text-green-800",
      subHeader: "text-green-600",
      itemsDescription: "text-gray-100",
      button: { from: "green", to: "blue" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה ספורט שמעת?",
    challengeIcon: "⚽🏀🎾🏊",
    challengeDescription: "בחר את הספורט הנכון!",
    itemLabel: "ספורט",
    tip: "💡 טיפ: תשמע את שם הספורט!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הספורט למטה לשמוע את השמות",
  },

  "magic-fairy-tales": {
    title: "🧚 משחק אגדות קסם ✨",
    subTitle: "הכנס לעולם של נסיכות וקוסמים!",
    itemsTitle: "דמויות האגדה שנלמד:",
    itemsDescription: "לחץ על דמות כדי לשמוע עליה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו דמות אגדה אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלה" },
      { icon: "👆", title: "3. תלחץ", description: "על הדמות הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו דמות אגדה שמעת?",
    challengeIcon: "🧚👸🤴🏰",
    challengeDescription: "בחר את הדמות הנכונה!",
    itemLabel: "דמות אגדה",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הדמויות למטה לשמוע את השמות",
  },
  "space-adventure": {
    title: "🚀 משחק הרפתקאות בחלל 🌌",
    subTitle: "טוס אל הכוכבים וגלה את החלל!",
    itemsTitle: "עצמי החלל שנלמד:",
    itemsDescription: "לחץ על עצם כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה עצם חלל אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על העצם הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0c0c0c 0%, #1a1a2e 25%, #16213e 50%, #0f3460 75%, #533483 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה עצם חלל שמעת?",
    challengeIcon: "🚀🌌⭐🪐",
    challengeDescription: "בחר את העצם הנכון!",
    itemLabel: "עצם חלל",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על עצמי החלל למטה לשמוע את השמות",
  },
  "cooking-kitchen": {
    title: "👨‍🍳 משחק בישול במטבח 🍳",
    subTitle: "למד על כלי מטבח ובישול!",
    itemsTitle: "כלי המטבח שנלמד:",
    itemsDescription: "לחץ על כלי כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה כלי מטבח אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על הכלי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff6b6b 0%, #feca57 25%, #48dbfb 50%, #ff9ff3 75%, #54a0ff 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה כלי מטבח שמעת?",
    challengeIcon: "👨‍🍳🍳🍲🥄",
    challengeDescription: "בחר את הכלי הנכון!",
    itemLabel: "כלי מטבח",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על כלי המטבח למטה לשמוע את השמות",
  },
  "circus-show": {
    title: "🎪 משחק מופע קרקס 🤡",
    subTitle: "הכנס לעולם הקרקס המרתק!",
    itemsTitle: "אומני הקרקס שנלמד:",
    itemsDescription: "לחץ על אומן כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה אומן קרקס אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על האומן הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff7675 0%, #fdcb6e 25%, #e17055 50%, #6c5ce7 75%, #74b9ff 100%)",
      header: "text-white",
      subHeader: "text-red-100",
      itemsDescription: "text-red-100",
      button: { from: "red", to: "yellow" },
      stepsBg: "bg-red-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה אומן קרקס שמעת?",
    challengeIcon: "🎪🤡🐘🦁",
    challengeDescription: "בחר את האומן הנכון!",
    itemLabel: "אומן קרקס",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על האומנים למטה לשמוע את השמות",
  },
  "superheroes": {
    title: "🦸 משחק גיבורי על ⚡",
    subTitle: "למד על כוחות סופר!",
    itemsTitle: "כוחות הגיבורים שנלמד:",
    itemsDescription: "לחץ על כוח כדי לגלות עליו!",
    steps: [
      { icon: "⚡", title: "1. תראה", description: "איזה כוח אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם הכוח" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הכוח הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #f7971e 0%, #ffd200 50%, #FF512F 100%)",
      header: "text-white",
      subHeader: "text-yellow-100",
      itemsDescription: "text-yellow-100",
      button: { from: "yellow", to: "orange" },
      stepsBg: "bg-yellow-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה כוח סופר זה?",
    challengeIcon: "🦸⚡🛡️🔥",
    challengeDescription: "זהה את כוח הגיבור ובחר את התשובה הנכונה!",
    itemLabel: "כוח",
    tip: "💡 טיפ: חשוב על הסמל!",
    tipDescription: "לכל כוח יש סמל ייחודי שעוזר לזהות אותו",
  },
  "art-craft": {
    title: "🎨 משחק אמנות ויצירה ✏️",
    subTitle: "הכר כלי אמנות!",
    itemsTitle: "כלי האמנות שנלמד:",
    itemsDescription: "לחץ על כלי כדי לגלות עליו!",
    steps: [
      { icon: "🎨", title: "1. תראה", description: "איזה כלי אמנות אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם הכלי" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הכלי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #f953c6 0%, #b91d73 50%, #fc5c7d 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "rose" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה כלי אמנות זה?",
    challengeIcon: "🎨✏️✂️🖌️",
    challengeDescription: "זהה את כלי האמנות ובחר את התשובה הנכונה!",
    itemLabel: "כלי",
    tip: "💡 טיפ: למד ליצור!",
    tipDescription: "כלי אמנות שונים יוצרים אפקטים ויצירות שונות",
  },
  "fairy-tale-chars": {
    title: "🧚 דמויות מאגדות 👸",
    subTitle: "הכר דמויות קסומות!",
    itemsTitle: "דמויות האגדה שנלמד:",
    itemsDescription: "לחץ על דמות כדי לגלות עליה!",
    steps: [
      { icon: "🧚", title: "1. תראה", description: "איזו דמות אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם הדמות" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הדמות הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)",
      header: "text-white",
      subHeader: "text-violet-100",
      itemsDescription: "text-violet-100",
      button: { from: "violet", to: "purple" },
      stepsBg: "bg-violet-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "מי הדמות הקסומה הזו?",
    challengeIcon: "🧚👸🐉🦄",
    challengeDescription: "זהה את דמות האגדה ובחר את התשובה הנכונה!",
    itemLabel: "דמות",
    tip: "💡 טיפ: זכור את האגדות!",
    tipDescription: "כל דמות מגיעה מאגדה מסוימת עם כוחות ייחודיים",
  },
};
