import type { GameUIConfig } from './gameUIConfig.types';

export const advancedConfigs: Partial<Record<string, GameUIConfig>> = {
  "virtual-reality": {
    title: "🥽 משחק מציאות מדומה 🌐",
    subTitle: "גלה את עולם הטכנולוגיה המתקדמת!",
    itemsTitle: "טכנולוגיות VR שנלמד:",
    itemsDescription: "לחץ על טכנולוגיה כדי לשמוע עליה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו טכנולוגיה אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלה" },
      { icon: "👆", title: "3. תלחץ", description: "על הטכנולוגיה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "purple" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו טכנולוגיה שמעת?",
    challengeIcon: "🥽🌐💻🎮",
    challengeDescription: "בחר את הטכנולוגיה הנכונה!",
    itemLabel: "טכנולוגיה",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הטכנולוגיות למטה לשמוע את השמות",
  },
  "new-professions": {
    title: "👨‍💻 משחק מקצועות חדשים 👩‍🚀",
    subTitle: "מקצועות העתיד כבר כאן!",
    itemsTitle: "מקצועות העתיד שנלמד:",
    itemsDescription: "לחץ על מקצוע כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה מקצוע אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על המקצוע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #00c9ff 0%, #92fe9d 25%, #00d2ff 50%, #3a7bd5 75%, #00d2ff 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "cyan", to: "blue" },
      stepsBg: "bg-cyan-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה מקצוע שמעת?",
    challengeIcon: "👨‍💻👩‍🚀🤖🎯",
    challengeDescription: "בחר את המקצוע הנכון!",
    itemLabel: "מקצוע",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המקצועות למטה לשמוע את השמות",
  },
  "advanced-weather": {
    title: "🌪️ משחק מזג אוויר מתקדם ⚡",
    subTitle: "תופעות מזג אוויר מרהיבות!",
    itemsTitle: "תופעות מזג אוויר שנלמד:",
    itemsDescription: "לחץ על תופעה כדי לשמוע עליה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו תופעה אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלה" },
      { icon: "👆", title: "3. תלחץ", description: "על התופעה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #74b9ff 0%, #0984e3 25%, #6c5ce7 50%, #a29bfe 75%, #fd79a8 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו תופעת מזג אוויר שמעת?",
    challengeIcon: "🌪️⚡🌀❄️",
    challengeDescription: "בחר את התופעה הנכונה!",
    itemLabel: "תופעת מזג אוויר",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על התופעות למטה לשמוע את השמות",
  },
  "advanced-colors": {
    title: "🎨 משחק צבעים מתקדם 💎",
    subTitle: "גוונים וצבעים מיוחדים!",
    itemsTitle: "צבעים מיוחדים שנלמד:",
    itemsDescription: "לחץ על צבע כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה צבע אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על הצבע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff7675 0%, #fdcb6e 25%, #6c5ce7 50%, #00b894 75%, #e17055 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "red" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה צבע שמעת?",
    challengeIcon: "🎨💎🪸🟣",
    challengeDescription: "בחר את הצבע הנכון!",
    itemLabel: "צבע",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצבעים למטה לשמוע את השמות",
  },
  "jewish-holidays": {
    title: "🕯️ משחק חגים יהודיים 📜",
    subTitle: "למד על חגי ישראל המיוחדים!",
    itemsTitle: "חגים יהודיים שנלמד:",
    itemsDescription: "לחץ על חג כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה חג אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על החג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 25%, #ff9a9e 50%, #fecfef 75%, #fecfef 100%)",
      header: "text-purple-800",
      subHeader: "text-purple-700",
      itemsDescription: "text-purple-700",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה חג יהודי שמעת?",
    challengeIcon: "🕯️📜✡️🍯",
    challengeDescription: "בחר את החג הנכון!",
    itemLabel: "חג יהודי",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על החגים למטה לשמוע את השמות",
  },
  "logic-games": {
    title: "🧩 משחק משחקי לוגיקה 🎯",
    subTitle: "פתח את כושר החשיבה שלך!",
    itemsTitle: "משחקי לוגיקה שנלמד:",
    itemsDescription: "לחץ על משחק כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה משחק אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על המשחק הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-indigo-100",
      itemsDescription: "text-indigo-100",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה משחק לוגיקה שמעת?",
    challengeIcon: "🧩🎯♟️🎲",
    challengeDescription: "בחר את המשחק הנכון!",
    itemLabel: "משחק לוגיקה",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המשחקים למטה לשמוע את השמות",
  },
  "sound-imitation": {
    title: "🎤 משחק חיקוי קולות ורעשים 🔊",
    subTitle: "חקה קולות וגלה את עולם הצלילים!",
    itemsTitle: "קולות ורעשים שנלמד:",
    itemsDescription: "לחץ על פריט כדי לשמוע את הקול שלו!",
    steps: [
      { icon: "🎧", title: "1. תשמע", description: "איזה קול אני משמיע" },
      { icon: "🎤", title: "2. תחקה", description: "נסה לחקות את הקול" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התמונה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #56ab2f 0%, #a8e6a1 25%, #56ab2f 50%, #7bb33f 75%, #4a934a 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה קול שמעת?",
    challengeIcon: "🎤🔊🎵🔉",
    challengeDescription: "חקה את הקול ובחר את התמונה הנכונה!",
    itemLabel: "קול",
    tip: "💡 טיפ: תקשיב בעיון לקול!",
    tipDescription: "חקה את הקול שאתה שומע ואז בחר את התמונה המתאימה",
  },
  "touch-senses": {
    title: "🤚 משחק מגע וחושים 🌡️",
    subTitle: "חקור מרקמים וחושים מרתקים!",
    itemsTitle: "חושים ומרקמים שנלמד:",
    itemsDescription: "לחץ על פריט כדי לדמיין את החושים!",
    steps: [
      { icon: "🤚", title: "1. תרגיש", description: "דמיין איך זה מרגיש" },
      { icon: "🧠", title: "2. תחשוב", description: "איזה חוש זה מפעיל" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #f093fb 0%, #f5576c 25%, #4facfe 50%, #00f2fe 75%, #43e97b 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-4 gap-4 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה חוש הפעלת?",
    challengeIcon: "🤚🌡️👃👅",
    challengeDescription: "דמיין את החוש ובחר את התשובה הנכונה!",
    itemLabel: "חוש",
    tip: "💡 טיפ: השתמש בדמיון!",
    tipDescription: "דמיין איך זה מרגיש, נשמע או נראה, ואז בחר",
  },
  "emotional-social": {
    title: "💖 משחק מציאות רגשית וחברתית 🤝",
    subTitle: "פתח אינטליגנציה רגשית וחברתית!",
    itemsTitle: "רגשות ומצבים שנלמד:",
    itemsDescription: "לחץ על רגש כדי להבין אותו!",
    steps: [
      { icon: "💭", title: "1. תחשוב", description: "איך אתה מרגיש במצב הזה" },
      { icon: "💖", title: "2. תהבן", description: "מה הרגש הזה אומר" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הרגש הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "pink" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-5xl mx-auto",
    },
    challengeTitle: "איזה רגש זה?",
    challengeIcon: "💖🤝😊😢",
    challengeDescription: "הבן את הרגש ובחר את התשובה הנכונה!",
    itemLabel: "רגש",
    tip: "💡 טיפ: תחבר לרגש שלך!",
    tipDescription: "חשוב על זמן שהרגשת כך, ואז בחר את הרגש המתאים",
  },
  "time-clock": {
    title: "⏰ משחק זמן ושעות היום 📅",
    subTitle: "למד על זמן, שעות וזמנים מיוחדים!",
    itemsTitle: "מושגי זמן שנלמד:",
    itemsDescription: "לחץ על מושג זמן כדי ללמוד עליו!",
    steps: [
      { icon: "🕐", title: "1. תראה", description: "איזה זמן אני מציג" },
      { icon: "🧠", title: "2. תחשוב", description: "מתי זה קורה ביום" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הזמן הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #4facfe 0%, #00f2fe 25%, #43e97b 50%, #38f9d7 75%, #667eea 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "cyan" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-4 gap-4 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה זמן זה?",
    challengeIcon: "⏰📅🌅🌙",
    challengeDescription: "זהה את הזמן ובחר את התשובה הנכונה!",
    itemLabel: "זמן",
    tip: "💡 טיפ: חשוב על היום שלך!",
    tipDescription: "חשוב מה אתה עושה בזמנים שונים ביום, ואז בחר",
  },
};
