import type { GameUIConfig } from './gameUIConfig.types';

export const photoQuizConfigs: Partial<Record<string, GameUIConfig>> = {
  "flags": {
    title: "🌍 משחק דגלי מדינות",
    subTitle: "זהה את הדגל של כל מדינה!",
    itemsTitle: "מדינות העולם שלנו:",
    itemsDescription: "לחץ על המדינה הנכונה!",
    steps: [
      { icon: "🌍", title: "1. תראה", description: "איזה דגל מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם המדינה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על המדינה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "של איזו מדינה הדגל הזה?",
    challengeIcon: "🌍🗺️🌐",
    challengeDescription: "זהה את הדגל ובחר את התשובה הנכונה!",
    itemLabel: "מדינה",
    tip: "💡 טיפ: שים לב לצבעים!",
    tipDescription: "לכל דגל יש צבעים וסמלים ייחודיים שעוזרים לזהות את המדינה",
  },
  "soccer-logos": {
    title: "⚽ משחק סמלי כדורגל",
    subTitle: "זהה את הסמל של כל קבוצה!",
    itemsTitle: "קבוצות הכדורגל שלנו:",
    itemsDescription: "לחץ על הקבוצה הנכונה!",
    steps: [
      { icon: "⚽", title: "1. תראה", description: "איזה סמל מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הקבוצה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הקבוצה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1e3a5f 0%, #0d2137 50%, #0a1628 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "של איזו קבוצה הסמל הזה?",
    challengeIcon: "⚽🏆🥅",
    challengeDescription: "זהה את סמל הקבוצה ובחר את התשובה הנכונה!",
    itemLabel: "קבוצה",
    tip: "💡 טיפ: שים לב לצבעים ולסמל!",
    tipDescription: "לכל קבוצה יש סמל וצבעים ייחודיים",
  },
  "car-brands": {
    title: "🚗 לוגואים של מכוניות",
    subTitle: "זהה את הלוגו של כל מותג!",
    itemsTitle: "מותגי המכוניות שלנו:",
    itemsDescription: "לחץ על המותג הנכון!",
    steps: [
      { icon: "🚗", title: "1. תראה", description: "איזה לוגו מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם המותג" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על המותג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזה מותג הלוגו הזה?",
    challengeIcon: "🚗🏎️🚙",
    challengeDescription: "זהה את לוגו המכונית ובחר את התשובה הנכונה!",
    itemLabel: "מותג",
    tip: "💡 טיפ: שים לב לצורת הלוגו!",
    tipDescription: "לכל מותג יש צורה וסימן ייחודיים שעוזרים לזהות אותו",
  },
  "world-landmarks": {
    title: "🏙️ אתרים מפורסמים בעולם",
    subTitle: "זהה את האתר המפורסם של כל מדינה!",
    itemsTitle: "אתרים מפורסמים בעולם:",
    itemsDescription: "לחץ על האתר הנכון!",
    steps: [
      { icon: "🏙️", title: "1. תראה", description: "איזה אתר מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם האתר" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על האתר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #2d1b69 0%, #11998e 100%)",
      header: "text-white",
      subHeader: "text-teal-100",
      itemsDescription: "text-teal-100",
      button: { from: "teal", to: "cyan" },
      stepsBg: "bg-teal-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה אתר מפורסם זה?",
    challengeIcon: "🏙️🗺️✈️",
    challengeDescription: "זהה את האתר המפורסם ובחר את התשובה הנכונה!",
    itemLabel: "אתר",
    tip: "💡 טיפ: זכור את המדינה!",
    tipDescription: "כל אתר מפורסם קשור למדינה או עיר מסויימת",
  },
  "solar-system": {
    title: "🪐 מערכת השמש",
    subTitle: "זהה כוכבי לכת וגרמי שמיים!",
    itemsTitle: "גרמי השמיים:",
    itemsDescription: "לחץ על גרם השמיים הנכון!",
    steps: [
      { icon: "🪐", title: "1. תראה", description: "איזה גרם שמיים מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את השם" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0d0d2b 0%, #1a1a6e 100%)",
      header: "text-yellow-200",
      subHeader: "text-indigo-200",
      itemsDescription: "text-indigo-200",
      button: { from: "indigo", to: "purple" },
      stepsBg: "bg-indigo-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גרם שמיים זה?",
    challengeIcon: "🪐⭐🌌",
    challengeDescription: "זהה את גרם השמיים ובחר את התשובה הנכונה!",
    itemLabel: "גרם שמיים",
    tip: "💡 טיפ: שים לב לצבע ולגודל!",
    tipDescription: "לכל כוכב לכת צבע וגודל ייחודיים",
  },
  "famous-paintings": {
    title: "🖼️ ציורים מפורסמים",
    subTitle: "זהה ציורים אגדיים מהיסטוריית האמנות!",
    itemsTitle: "ציורים מפורסמים:",
    itemsDescription: "לחץ על הציור הנכון!",
    steps: [
      { icon: "🖼️", title: "1. תראה", description: "איזה ציור מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הציור" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הציור הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #3d1c02 0%, #7b4f1e 100%)",
      header: "text-amber-100",
      subHeader: "text-amber-200",
      itemsDescription: "text-amber-200",
      button: { from: "amber", to: "orange" },
      stepsBg: "bg-amber-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה ציור מפורסם זה?",
    challengeIcon: "🖼️🎨🖌️",
    challengeDescription: "זהה את הציור המפורסם ובחר את התשובה הנכונה!",
    itemLabel: "ציור",
    tip: "💡 טיפ: זכור את הציירים הגדולים!",
    tipDescription: "כל ציור שייך לאמן גדול מהיסטוריית האמנות",
  },
  "tech-logos": {
    title: "📱 לוגואים של טכנולוגיה",
    subTitle: "זהה לוגואים של חברות הטכנולוגיה הגדולות!",
    itemsTitle: "חברות טכנולוגיה:",
    itemsDescription: "לחץ על הלוגו הנכון!",
    steps: [
      { icon: "📱", title: "1. תראה", description: "איזה לוגו מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם החברה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הלוגו הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0369a1 0%, #1e3a5f 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "blue" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזו חברה זה הלוגו?",
    challengeIcon: "📱💻🌐",
    challengeDescription: "זהה את הלוגו של חברת הטכנולוגיה ובחר את התשובה הנכונה!",
    itemLabel: "חברה",
    tip: "💡 טיפ: שים לב לצורה ולצבע!",
    tipDescription: "לכל חברת טכנולוגיה יש לוגו ייחודי שקל לזהות",
  },
  "dog-breeds": {
    title: "🐕 גזעי כלבים",
    subTitle: "זהה גזעי כלבים מסביב לעולם!",
    itemsTitle: "גזעי כלבים:",
    itemsDescription: "לחץ על הכלב הנכון!",
    steps: [
      { icon: "🐕", title: "1. תראה", description: "איזה גזע כלב מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הגזע" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הכלב הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #92400e 0%, #d97706 100%)",
      header: "text-white",
      subHeader: "text-amber-100",
      itemsDescription: "text-amber-100",
      button: { from: "amber", to: "yellow" },
      stepsBg: "bg-amber-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גזע כלב זה?",
    challengeIcon: "🐕🦴🐾",
    challengeDescription: "זהה את גזע הכלב ובחר את התשובה הנכונה!",
    itemLabel: "גזע כלב",
    tip: "💡 טיפ: שים לב לגודל ולצורת הגוף!",
    tipDescription: "לכל גזע כלב מראה וגוף ייחודיים",
  },
  "cat-breeds": {
    title: "🐱 גזעי חתולים",
    subTitle: "זהה גזעי חתולים מסביב לעולם!",
    itemsTitle: "גזעי חתולים:",
    itemsDescription: "לחץ על החתול הנכון!",
    steps: [
      { icon: "🐱", title: "1. תראה", description: "איזה גזע חתול מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הגזע" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על החתול הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #4c1d95 0%, #6d28d9 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "violet" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה גזע חתול זה?",
    challengeIcon: "🐱😺🐾",
    challengeDescription: "זהה את גזע החתול ובחר את התשובה הנכונה!",
    itemLabel: "גזע חתול",
    tip: "💡 טיפ: שים לב לצורת הפנים ולפרווה!",
    tipDescription: "לכל גזע חתול מראה פרווה וגוף ייחודיים",
  },
  "nba-teams": {
    title: "🏀 קבוצות NBA",
    subTitle: "זהה לוגואים של קבוצות הכדורסל הגדולות!",
    itemsTitle: "קבוצות NBA:",
    itemsDescription: "לחץ על הלוגו הנכון!",
    steps: [
      { icon: "🏀", title: "1. תראה", description: "של איזה קבוצה הלוגו?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הקבוצה" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הלוגו הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #7c2d12 0%, #c2410c 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "של איזו קבוצת NBA זה הלוגו?",
    challengeIcon: "🏀🏆🌟",
    challengeDescription: "זהה את לוגו קבוצת ה-NBA ובחר את התשובה הנכונה!",
    itemLabel: "קבוצה",
    tip: "💡 טיפ: זכור את הצבעים של כל קבוצה!",
    tipDescription: "לכל קבוצת NBA צבעים וסמל ייחודיים",
  },
  "exotic-birds": {
    title: "🦩 ציפורים אקזוטיות",
    subTitle: "זהה ציפורים מפורסמות מסביב העולם!",
    itemsTitle: "ציפורים אקזוטיות:",
    itemsDescription: "לחץ על הציפור הנכון!",
    steps: [
      { icon: "🦩", title: "1. תראה", description: "איזו ציפור מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הציפור" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #0c4a6e 0%, #0284c7 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "cyan" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזו ציפור זה?",
    challengeIcon: "🦩🦥🦜",
    challengeDescription: "זהה את הציפור ובחר את התשובה הנכונה!",
    itemLabel: "ציפור",
    tip: "💡 טיפ: שים לב לצבע ולצורת הגוף!",
    tipDescription: "לכל ציפור צבעים ותכונות ייחודיות",
  },
  "butterflies": {
    title: "🦋 פרפרים",
    subTitle: "זהה פרפרים צבעוניים מסביב העולם!",
    itemsTitle: "פרפרים:",
    itemsDescription: "לחץ על הפרפר הנכון!",
    steps: [
      { icon: "🦋", title: "1. תראה", description: "איזה פרפר מוצג?" },
      { icon: "🔊", title: "2. תשמע", description: "שמע את שם הפרפר" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התשובה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #831843 0%, #ec4899 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "rose" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: { className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto" },
    challengeTitle: "איזה פרפר זה?",
    challengeIcon: "🦋🌸🌿",
    challengeDescription: "זהה את הפרפר ובחר את התשובה הנכונה!",
    itemLabel: "פרפר",
    tip: "💡 טיפ: שים לב לצבע ולצורת הכנפיים!",
    tipDescription: "לכל פרפר כנפיים בצבעים ודוגמאות ייחודיים",
  },
};
