import type { GameUIConfig } from './gameUIConfig.types';

export const natureConfigs: Partial<Record<string, GameUIConfig>> = {
  fruits: {
    title: "🍎 משחק פירות 🍌",
    subTitle: "למד פירות דרך שמיעה!",
    itemsTitle: "כל הפירות שנלמד:",
    itemsDescription: "לחץ על פרי כדי לשמוע את השם שלו! פירות טעימים ובריאים",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה פרי אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הפרי נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על הפרי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffeaa7 0%, #fab1a0 25%, #e17055 50%, #fdcb6e 75%, #f39c12 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-5 gap-4 max-w-4xl mx-auto",
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה פרי שמעת?",
    challengeIcon: "🍎🍌🍊🥝",
    challengeDescription: "בחר את הפרי הנכון!",
    itemLabel: "פרי",
    tip: "💡 טיפ: תשמע את שם הפרי הטעים!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הפירות למטה לשמוע את השמות",
  },

  animals: {
    title: "🐶 משחק חיות 🐱",
    subTitle: "למד חיות דרך שמיעה!",
    itemsTitle: "כל החיות שנלמד:",
    itemsDescription: "לחץ על חיה כדי לשמוע את השם שלה! חיות מקסימות",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזו חיה אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך החיה נראית" },
      { icon: "👆", title: "3. תלחץ", description: "על החיה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #d4f1d4 0%, #a8e6a8 25%, #7dd87d 50%, #52c952 75%, #10b981 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזו חיה שמעת?",
    challengeIcon: "🐾🐄🐶🐱",
    challengeDescription: "בחר את החיה הנכונה!",
    itemLabel: "חיה",
    tip: "💡 טיפ: תשמע את שם החיה שאני אומר!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על החיות למטה לשמוע את השמות",
    // 🔍 מטאדאטה SEO
    metadata: {
      keywords: "משחק חיות לילדים, למידת בעלי חיים, משחקים חינוכיים, גיל 2-5, פעוטות, חיות בעברית",
      description: "משחק אינטראקטיבי ללימוד בעלי חיים לילדים בגילאי 2-5. למדו על חיות שונות בעברית דרך משחק מהנה!",
    },
  },

  vegetables: {
    title: "🥕 משחק ירקות 🥬",
    subTitle: "למד ירקות באמצעות הקשבה!",
    itemsTitle: "כל הירקות שנלמד:",
    itemsDescription: "לחץ על ירק כדי לשמוע את שמו! ירקות בריאים וטעימים",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה ירק אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הירק נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על הירק הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #d4f1d4 0%, #a8e6a8 25%, #7dd87d 50%, #52c952 75%, #16a34a 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה ירק שמעת?",
    challengeIcon: "🥕🥬🍅🥒",
    challengeDescription: "בחר את הירק הנכון!",
    itemLabel: "ירק",
    tip: "💡 טיפ: תשמע את שם הירק הבריא!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הירקות למטה לשמוע את השמות",
  },

  weather: {
    title: "🌤️ משחק מזג אוויר ☔",
    subTitle: "למד מזג אוויר דרך שמיעה!",
    itemsTitle: "כל מזגי האוויר שנלמד:",
    itemsDescription: "לחץ על מזג אוויר כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מזג אוויר אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך מזג האוויר נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על מזג האוויר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #87CEEB 0%, #98D8E8 25%, #B0E0E6 50%, #E0F6FF 75%, #F0F8FF 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "blue" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה מזג אוויר שמעת?",
    challengeIcon: "🌤️☔🌞❄️",
    challengeDescription: "בחר את מזג האוויר הנכון!",
    itemLabel: "מזג אוויר",
    tip: "💡 טיפ: תשמע את מזג האוויר!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על מזגי האוויר למטה לשמוע את השמות",
  },

  space: {
    title: "🚀 משחק חלל 🌟",
    subTitle: "למד על החלל דרך שמיעה!",
    itemsTitle: "חפצי החלל שנלמד:",
    itemsDescription: "לחץ על חפץ חלל כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה חפץ חלל אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הוא נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על חפץ החלל הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1e1b4b 0%, #312e81 25%, #3730a3 50%, #1e40af 75%, #1d4ed8 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  dinosaurs: {
    title: "🦕 משחק דינוזאורים 🦕",
    subTitle: "למד על דינוזאורים מדהימים מהעבר!",
    itemsTitle: "הדינוזאורים שנלמד:",
    itemsDescription: "לחץ על דינוזאור כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה דינוזאור אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם הדינוזאור" },
      { icon: "👆", title: "3. תלחץ", description: "על הדינוזאור הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-green-800",
      subHeader: "text-green-600",
      itemsDescription: "text-gray-100",
      button: { from: "green", to: "teal" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה דינוזאור שמעת?",
    challengeIcon: "🦕🦖🦴🌋",
    challengeDescription: "בחר את הדינוזאור הנכון!",
    itemLabel: "דינוזאור",
    tip: "💡 טיפ: תשמע את שם הדינוזאור!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הדינוזאורים למטה לשמוע את השמות",
  },

  "world-food": {
    title: "🌍 משחק אוכל מהעולם 🍕",
    subTitle: "למד על מאכלים מתרבויות שונות!",
    itemsTitle: "המאכלים שנלמד:",
    itemsDescription: "לחץ על מאכל כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה מאכל אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם המאכל" },
      { icon: "👆", title: "3. תלחץ", description: "על המאכל הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff6b6b 0%, #feca57 25%, #48dbfb 50%, #ff9ff3 75%, #54a0ff 100%)",
      header: "text-white",
      subHeader: "text-red-100",
      itemsDescription: "text-red-100",
      button: { from: "red", to: "orange" },
      stepsBg: "bg-red-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה מאכל עולמי שמעת?",
    challengeIcon: "🍕🍜🌮🍱",
    challengeDescription: "בחר את המאכל הנכון!",
    itemLabel: "מאכל",
    tip: "💡 טיפ: תשמע את שם המאכל!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על המאכלים למטה לשמוע את השמות",
  },

  recycling: {
    title: "♻️ משחק מיחזור ♻️",
    subTitle: "למד על מיחזור והגנת הסביבה!",
    itemsTitle: "החומרים למיחזור שנלמד:",
    itemsDescription: "לחץ על חומר כדי לשמוע איך למחזר אותו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה חומר אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "איך למחזר אותו" },
      { icon: "👆", title: "3. תלחץ", description: "על החומר הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #2ecc71 0%, #27ae60 25%, #16a085 50%, #48c9b0 75%, #52d681 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "emerald" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה חומר למיחזור שמעת?",
    challengeIcon: "♻️🗂️📦🍃",
    challengeDescription: "בחר את החומר הנכון!",
    itemLabel: "חומר למיחזור",
    tip: "💡 טיפ: תשמע איך למחזר!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על החומרים למטה לשמוע את השמות",
  },

  "ocean-life": {
    title: "🌊 משחק חיי ים 🐟",
    subTitle: "גלה בעלי חיים ימיים מרתקים!",
    itemsTitle: "בעלי החיים הימיים שנלמד:",
    itemsDescription: "לחץ על בעל חיים כדי לשמוע עליו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה בעל חיים ימי אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על בעל החיים הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1e3c72 0%, #2a5298 25%, #667eea 50%, #764ba2 75%, #f093fb 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "cyan" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה בעל חיים ימי שמעת?",
    challengeIcon: "🌊🐟🐬🦈",
    challengeDescription: "בחר את בעל החיים הנכון!",
    itemLabel: "בעל חיים ימי",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על בעלי החיים למטה לשמוע את השמות",
  },
  "garden-plants": {
    title: "🌺 משחק צמחי גן 🌻",
    subTitle: "למד על פרחים וצמחים יפים!",
    itemsTitle: "הצמחים והפרחים שנלמד:",
    itemsDescription: "לחץ על צמח כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה צמח או פרח אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "את השם שלו" },
      { icon: "👆", title: "3. תלחץ", description: "על הצמח הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #56ab2f 0%, #a8e6cf 25%, #ff8a80 50%, #ffcc80 75%, #ce93d8 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "pink" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה צמח או פרח שמעת?",
    challengeIcon: "🌺🌻🌹🌷",
    challengeDescription: "בחר את הצמח הנכון!",
    itemLabel: "צמח או פרח",
    tip: "💡 טיפ: תשמע את השם!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הצמחים למטה לשמוע את השמות",
  },
  "climate-planet": {
    title: "🌍 משחק אקלים וכדור הארץ 🌿",
    subTitle: "גלה את כדור הארץ והאקלים שלו!",
    itemsTitle: "אזורי אקלים ויבשות שנלמד:",
    itemsDescription: "לחץ על מקום כדי לגלות עליו!",
    steps: [
      { icon: "🌍", title: "1. תראה", description: "איזה מקום בעולם אני מציג" },
      { icon: "🌡️", title: "2. תחשוב", description: "איך האקלים שם" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על המקום הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #56ab2f 0%, #a8e6a1 25%, #4facfe 50%, #00f2fe 75%, #43e97b 100%)",
      header: "text-white",
      subHeader: "text-emerald-100",
      itemsDescription: "text-emerald-100",
      button: { from: "emerald", to: "green" },
      stepsBg: "bg-emerald-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה מקום בעולם זה?",
    challengeIcon: "🌍🌿🏔️🏖️",
    challengeDescription: "זהה את המקום והאקלים ובחר את התשובה הנכונה!",
    itemLabel: "מקום",
    tip: "💡 טיפ: חשוב על האקלים!",
    tipDescription: "חשוב איך מרגיש האקלים במקום הזה, ואז בחר",
  },
  "birds": {
    title: "🦅 משחק ציפורים 🐦",
    subTitle: "הכר ציפורים מרחבי העולם!",
    itemsTitle: "הציפורים שנלמד:",
    itemsDescription: "לחץ על ציפור כדי לגלות עליה!",
    steps: [
      { icon: "🦅", title: "1. תראה", description: "איזו ציפור אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם הציפור" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הציפור הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #56CCF2 0%, #2F80ED 50%, #87CEEB 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "blue" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזו ציפור זו?",
    challengeIcon: "🦅🐦🦜🦩",
    challengeDescription: "זהה את הציפור ובחר את התשובה הנכונה!",
    itemLabel: "ציפור",
    tip: "💡 טיפ: שים לב לצבעים!",
    tipDescription: "כל ציפור ייחודית בצבעיה ואורח חייה",
  },
  "bugs-insects": {
    title: "🦋 חרקים ופרפרים 🐛",
    subTitle: "עולם זעיר ומרתק!",
    itemsTitle: "החרקים שנלמד:",
    itemsDescription: "לחץ על חרק כדי לגלות עליו!",
    steps: [
      { icon: "🦋", title: "1. תראה", description: "איזה חרק אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם החרק" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על החרק הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #84fab0 0%, #8fd3f4 50%, #a1c4fd 100%)",
      header: "text-white",
      subHeader: "text-lime-100",
      itemsDescription: "text-lime-100",
      button: { from: "lime", to: "green" },
      stepsBg: "bg-lime-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה חרק זה?",
    challengeIcon: "🦋🐝🐛🐞",
    challengeDescription: "זהה את החרק ובחר את התשובה הנכונה!",
    itemLabel: "חרק",
    tip: "💡 טיפ: שימו לב לכנפיים!",
    tipDescription: "לכל חרק סימנים ייחודיים שעוזרים לזהות אותו",
  },
  "camping": {
    title: "⛺ משחק טיול ושטח 🗺️",
    subTitle: "הכן ציוד לטיול!",
    itemsTitle: "ציוד הטיול שנלמד:",
    itemsDescription: "לחץ על פריט כדי לגלות עליו!",
    steps: [
      { icon: "⛺", title: "1. תראה", description: "איזה ציוד טיול אני מציג" },
      { icon: "👂", title: "2. תשמע", description: "שמע את שם הציוד" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על הציוד הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #134E5E 0%, #71B280 50%, #52c234 100%)",
      header: "text-white",
      subHeader: "text-emerald-100",
      itemsDescription: "text-emerald-100",
      button: { from: "emerald", to: "green" },
      stepsBg: "bg-emerald-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl mx-auto",
    },
    challengeTitle: "איזה ציוד טיול זה?",
    challengeIcon: "⛺🎒🔦🗺️",
    challengeDescription: "זהה את ציוד הטיול ובחר את התשובה הנכונה!",
    itemLabel: "ציוד",
    tip: "💡 טיפ: תתכונן היטב!",
    tipDescription: "ציוד טיול נכון יכול להציל חיים ולהפוך הרפתקאה לבטוחה",
  },
};
