import type { GameUIConfig } from './gameUIConfig.types';

export const homeLifeConfigs: Partial<Record<string, GameUIConfig>> = {
  transport: {
    title: "🚗 משחק תחבורה ✈️",
    subTitle: "למד כלי תחבורה דרך שמיעה!",
    itemsTitle: "כלי התחבורה שנלמד:",
    itemsDescription: "לחץ על כלי תחבורה כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה כלי תחבורה אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הוא נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על כלי התחבורה הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #3B82F6 0%, #1D4ED8 25%, #1E40AF 50%, #1E3A8A 75%, #312E81 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה כלי תחבורה שמעת?",
    challengeIcon: "🚗✈️🚢🚂",
    challengeDescription: "בחר את כלי התחבורה הנכון!",
    itemLabel: "כלי תחבורה",
    tip: "💡 טיפ: תשמע את שם כלי התחבורה!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על כלי התחבורה למטה לשמוע את השמות",
  },

  clothing: {
    title: "👕 משחק בגדים 👗",
    subTitle: "למד בגדים דרך שמיעה!",
    itemsTitle: "הבגדים שנלמד:",
    itemsDescription: "לחץ על בגד כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה בגד אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הבגד נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על הבגד הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fce7f3 0%, #f9a8d4 25%, #ec4899 50%, #db2777 75%, #be185d 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "rose" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
    // ✨ הוספות עבור AutoGamePage
    challengeTitle: "איזה בגד שמעת?",
    challengeIcon: "👕👗👖👚",
    challengeDescription: "בחר את הבגד הנכון!",
    itemLabel: "בגד",
    tip: "💡 טיפ: תשמע את שם הבגד!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הבגדים למטה לשמוע את השמות",
  },

  'smells-tastes': {
    title: "👃 משחק ריחות וטעמים 👅",
    subTitle: "למד ריחות וטעמים דרך שמיעה!",
    itemsTitle: "הריחות והטעמים שנלמד:",
    itemsDescription: "לחץ על ריח או טעם כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה טעם או ריח אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך זה מרגיש" },
      { icon: "👆", title: "3. תלחץ", description: "על הטעם הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fef7cd 0%, #fbbf24 25%, #f59e0b 50%, #d97706 75%, #b45309 100%)",
      header: "text-white",
      subHeader: "text-amber-100",
      itemsDescription: "text-amber-100",
      button: { from: "amber", to: "orange" },
      stepsBg: "bg-amber-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  house: {
    title: "🏠 משחק הבית 🪑",
    subTitle: "למד חפצי בית דרך שמיעה!",
    itemsTitle: "חפצי הבית שנלמד:",
    itemsDescription: "לחץ על חפץ כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה חפץ בית אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך החפץ נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על החפץ הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #e0f2fe 0%, #7dd3fc 25%, #38bdf8 50%, #0ea5e9 75%, #0284c7 100%)",
      header: "text-white",
      subHeader: "text-sky-100",
      itemsDescription: "text-sky-100",
      button: { from: "sky", to: "blue" },
      stepsBg: "bg-sky-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  tools: {
    title: "🔧 משחק כלי עבודה ⚒️",
    subTitle: "למד כלי עבודה דרך שמיעה!",
    itemsTitle: "כלי העבודה שנלמד:",
    itemsDescription: "לחץ על כלי עבודה כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה כלי עבודה אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הכלי נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על הכלי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fef3c7 0%, #fbbf24 25%, #f59e0b 50%, #d97706 75%, #92400e 100%)",
      header: "text-white",
      subHeader: "text-yellow-100",
      itemsDescription: "text-yellow-100",
      button: { from: "yellow", to: "orange" },
      stepsBg: "bg-yellow-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  professions: {
    title: "👩‍⚕️ משחק מקצועות 👨‍🚒",
    subTitle: "למד מקצועות דרך שמיעה!",
    itemsTitle: "המקצועות שנלמד:",
    itemsDescription: "לחץ על מקצוע כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה מקצוע אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך המקצוע נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על המקצוע הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #fce7f3 0%, #e879f9 25%, #a855f7 50%, #7c3aed 75%, #5b21b6 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "indigo" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  vehicles: {
    title: "🚛 משחק כלי רכב 🏍️",
    subTitle: "למד כלי רכב דרך שמיעה!",
    itemsTitle: "כלי הרכב שנלמד:",
    itemsDescription: "לחץ על כלי רכב כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה כלי רכב אני אומר" },
      { icon: "🤔", title: "2. תחשוב", description: "איך הוא נראה" },
      { icon: "👆", title: "3. תלחץ", description: "על כלי הרכב הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #1e40af 0%, #3b82f6 25%, #60a5fa 50%, #93c5fd 75%, #dbeafe 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-3 md:grid-cols-4 gap-4 max-w-4xl mx-auto",
      showSpeaker: false,
    },
  },

  kitchen: {
    title: "👨‍🍳 משחק כלי מטבח 👨‍🍳",
    subTitle: "למד על כלי מטבח ובישול!",
    itemsTitle: "כלי המטבח שנלמד:",
    itemsDescription: "לחץ על כלי כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה כלי מטבח אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם הכלי" },
      { icon: "👆", title: "3. תלחץ", description: "על הכלי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 25%, #a8e6cf 50%, #dcedc1 75%, #ffd3e1 100%)",
      header: "text-orange-800",
      subHeader: "text-orange-600",
      itemsDescription: "text-gray-100",
      button: { from: "orange", to: "red" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה כלי מטבח שמעת?",
    challengeIcon: "🍲🍳🔪🥄",
    challengeDescription: "בחר את הכלי הנכון!",
    itemLabel: "כלי מטבח",
    tip: "💡 טיפ: תשמע את שם הכלי!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הכלים למטה לשמוע את השמות",
  },

  "body-parts": {
    title: "👂 משחק חלקי הגוף 👂",
    subTitle: "למד על חלקי הגוף השונים!",
    itemsTitle: "חלקי הגוף שנלמד:",
    itemsDescription: "לחץ על חלק גוף כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה חלק גוף אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם חלק הגוף" },
      { icon: "👆", title: "3. תלחץ", description: "על חלק הגוף הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffd3e1 0%, #ffecd2 25%, #fcb69f 50%, #a8e6cf 75%, #dcedc1 100%)",
      header: "text-pink-800",
      subHeader: "text-pink-600",
      itemsDescription: "text-gray-100",
      button: { from: "pink", to: "purple" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה חלק גוף שמעת?",
    challengeIcon: "👁️👂👃✋",
    challengeDescription: "בחר את חלק הגוף הנכון!",
    itemLabel: "חלק גוף",
    tip: "💡 טיפ: תשמע את שם חלק הגוף!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על חלקי הגוף למטה לשמוע את השמות",
  },

  family: {
    title: "👨‍👩‍👧‍👦 משחק בני המשפחה 👨‍👩‍👧‍👦",
    subTitle: "למד על בני המשפחה השונים!",
    itemsTitle: "בני המשפחה שנלמד:",
    itemsDescription: "לחץ על בן משפחה כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה בן משפחה אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם בן המשפחה" },
      { icon: "👆", title: "3. תלחץ", description: "על בן המשפחה הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #a8e6cf 0%, #dcedc1 25%, #ffd3e1 50%, #ffecd2 75%, #fcb69f 100%)",
      header: "text-blue-800",
      subHeader: "text-blue-600",
      itemsDescription: "text-gray-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-white bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה בן משפחה שמעת?",
    challengeIcon: "👨👩👧👦",
    challengeDescription: "בחר את בן המשפחה הנכון!",
    itemLabel: "בן משפחה",
    tip: "💡 טיפ: תשמע את שם בן המשפחה!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על בני המשפחה למטה לשמוע את השמות",
  },

  medicine: {
    title: "💊 משחק כלי רפואה 🏥",
    subTitle: "למד על כלים רפואיים ובריאות!",
    itemsTitle: "הכלים הרפואיים שנלמד:",
    itemsDescription: "לחץ על כלי כדי לשמוע את השם שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה כלי רפואי אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "את שם הכלי" },
      { icon: "👆", title: "3. תלחץ", description: "על הכלי הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffffff 0%, #dbeafe 25%, #3b82f6 50%, #1e40af 75%, #1e3a8a 100%)",
      header: "text-white",
      subHeader: "text-blue-100",
      itemsDescription: "text-blue-100",
      button: { from: "blue", to: "indigo" },
      stepsBg: "bg-blue-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה כלי רפואי שמעת?",
    challengeIcon: "💊🩺🏥⚕️",
    challengeDescription: "בחר את הכלי הנכון!",
    itemLabel: "כלי רפואי",
    tip: "💡 טיפ: תשמע את שם הכלי!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הכלים למטה לשמוע את השמות",
  },

  "nature-sounds": {
    title: "🌿 משחק קולות הטבע 🦜",
    subTitle: "למד להכיר קולות מהטבע!",
    itemsTitle: "קולות הטבע שנלמד:",
    itemsDescription: "לחץ על קול כדי לשמוע אותו!",
    steps: [
      { icon: "👂", title: "1. תשמע", description: "איזה קול טבע אני משמיע" },
      { icon: "🤔", title: "2. תחשוב", description: "מה יוצר את הקול הזה" },
      { icon: "👆", title: "3. תלחץ", description: "על הקול הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #d4e6f1 0%, #a8cfd8 25%, #7fbeaa 50%, #6bb091 75%, #5ba378 100%)",
      header: "text-white",
      subHeader: "text-green-100",
      itemsDescription: "text-green-100",
      button: { from: "green", to: "teal" },
      stepsBg: "bg-green-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה קול טבע שמעת?",
    challengeIcon: "🌿🦜🌊🌬️",
    challengeDescription: "בחר את הקול הנכון!",
    itemLabel: "קול טבע",
    tip: "💡 טיפ: תשמע את קול הטבע!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הקולות למטה לשמוע אותם",
  },

  "seasons-holidays": {
    title: "🍂 משחק עונות וחגים 🎄",
    subTitle: "למד על עונות השנה והחגים!",
    itemsTitle: "העונות והחגים שנלמד:",
    itemsDescription: "לחץ על עונה או חג כדי לשמוע על זה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו עונה או חג אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "מה מיוחד בזה" },
      { icon: "👆", title: "3. תלחץ", description: "על העונה או החג הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ffd89b 0%, #19547b 25%, #ff8a80 50%, #ffccbc 75%, #b39ddb 100%)",
      header: "text-white",
      subHeader: "text-orange-100",
      itemsDescription: "text-orange-100",
      button: { from: "orange", to: "purple" },
      stepsBg: "bg-orange-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזו עונה או חג שמעת?",
    challengeIcon: "🍂❄️🌸☀️",
    challengeDescription: "בחר את העונה או החג הנכון!",
    itemLabel: "עונה או חג",
    tip: "💡 טיפ: תשמע על העונה או החג!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על העונות והחגים למטה לשמוע עליהם",
  },

  "shopping-money": {
    title: "🛒 משחק קניות וכסף 💰",
    subTitle: "למד על קניות וחשבון כסף!",
    itemsTitle: "פריטי הקניות שנלמד:",
    itemsDescription: "לחץ על פריט כדי לשמוע את המחיר שלו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה פריט אני מבקש" },
      { icon: "🎤", title: "2. תשמע", description: "כמה זה עולה" },
      { icon: "👆", title: "3. תלחץ", description: "על הפריט הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #f5576c 75%, #4facfe 100%)",
      header: "text-white",
      subHeader: "text-purple-100",
      itemsDescription: "text-purple-100",
      button: { from: "purple", to: "indigo" },
      stepsBg: "bg-purple-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה פריט לקניה שמעת?",
    challengeIcon: "🛒💰🛍️💳",
    challengeDescription: "בחר את הפריט הנכון!",
    itemLabel: "פריט לקניה",
    tip: "💡 טיפ: תשמע את המחיר!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הפריטים למטה לשמוע את המחירים",
  },
  "road-safety": {
    title: "🚦 משחק בטיחות בדרכים 🚗",
    subTitle: "למד על בטיחות וחוקי תנועה!",
    itemsTitle: "כללי הבטיחות שנלמד:",
    itemsDescription: "לחץ על כלל כדי לשמוע על חשיבותו!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזה כלל בטיחות אני מציג" },
      { icon: "🎤", title: "2. תשמע", description: "למה זה חשוב" },
      { icon: "👆", title: "3. תלחץ", description: "על הכלל הנכון" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff7675 0%, #fdcb6e 25%, #6c5ce7 50%, #74b9ff 75%, #00b894 100%)",
      header: "text-white",
      subHeader: "text-red-100",
      itemsDescription: "text-red-100",
      button: { from: "red", to: "yellow" },
      stepsBg: "bg-red-100 bg-opacity-90",
    },
    grid: {
      className: "flex flex-wrap justify-center gap-4",
    },
    challengeTitle: "איזה כלל בטיחות שמעת?",
    challengeIcon: "🚦🚗👮‍♂️⚠️",
    challengeDescription: "בחר את הכלל הנכון!",
    itemLabel: "כלל בטיחות",
    tip: "💡 טיפ: תשמע על הבטיחות!",
    tipDescription: "לחץ על הסמל למעלה כדי לשמוע שוב, או על הכללים למטה לשמוע עליהם",
  },
  "body-movements": {
    title: "🤸 משחק תנועות גוף וריקוד 💃",
    subTitle: "תזוז, תרקוד ותהנה מהגוף שלך!",
    itemsTitle: "תנועות שנלמד:",
    itemsDescription: "לחץ על תנועה כדי לראות איך לעשות אותה!",
    steps: [
      { icon: "👀", title: "1. תראה", description: "איזו תנועה אני מראה" },
      { icon: "🤸", title: "2. תבצע", description: "עשה את התנועה בעצמך" },
      { icon: "👆", title: "3. תבחר", description: "לחץ על התנועה הנכונה" },
    ],
    colors: {
      background: "linear-gradient(135deg, #ff6b6b 0%, #feca57 25%, #ff9ff3 50%, #54a0ff 75%, #5f27cd 100%)",
      header: "text-white",
      subHeader: "text-pink-100",
      itemsDescription: "text-pink-100",
      button: { from: "pink", to: "purple" },
      stepsBg: "bg-pink-100 bg-opacity-90",
    },
    grid: {
      className: "grid grid-cols-2 md:grid-cols-3 gap-6 max-w-5xl mx-auto",
    },
    challengeTitle: "איזו תנועה ביצעת?",
    challengeIcon: "🤸💃🧘‍♀️🕺",
    challengeDescription: "בצע את התנועה ובחר את התשובה הנכונה!",
    itemLabel: "תנועה",
    tip: "💡 טיפ: תזוז בבטחה!",
    tipDescription: "בצע את התנועה בזהירות ובחר את התנועה שביצעת",
  },
};
